dnasp Q0 2031 0 2.0 team1-TFIDF_bnn_bnn
clipping Q0 719 0 2.0 team1-TFIDF_bnn_bnn
versioning Q0 112 0 2.0 team1-TFIDF_bnn_bnn
benchmarking Q0 452 0 4.0 team1-TFIDF_bnn_bnn
benchmarking Q0 120 1 4.0 team1-TFIDF_bnn_bnn
gencode Q0 21 0 2.0 team1-TFIDF_bnn_bnn
sbs Q0 422 0 2.0 team1-TFIDF_bnn_bnn
csv Q0 1012 0 4.0 team1-TFIDF_bnn_bnn
csv Q0 2174 1 4.0 team1-TFIDF_bnn_bnn
bam Q0 2242 0 78.0 team1-TFIDF_bnn_bnn
bam Q0 2302 1 78.0 team1-TFIDF_bnn_bnn
bam Q0 453 2 78.0 team1-TFIDF_bnn_bnn
bam Q0 253 3 78.0 team1-TFIDF_bnn_bnn
bam Q0 587 4 78.0 team1-TFIDF_bnn_bnn
bam Q0 2363 5 78.0 team1-TFIDF_bnn_bnn
bam Q0 2106 6 78.0 team1-TFIDF_bnn_bnn
bam Q0 2101 7 78.0 team1-TFIDF_bnn_bnn
bam Q0 531 8 78.0 team1-TFIDF_bnn_bnn
bam Q0 1010 9 78.0 team1-TFIDF_bnn_bnn
bam Q0 2131 10 78.0 team1-TFIDF_bnn_bnn
bam Q0 2036 11 78.0 team1-TFIDF_bnn_bnn
bam Q0 908 12 78.0 team1-TFIDF_bnn_bnn
bam Q0 427 13 78.0 team1-TFIDF_bnn_bnn
bam Q0 280 14 78.0 team1-TFIDF_bnn_bnn
bam Q0 508 15 78.0 team1-TFIDF_bnn_bnn
bam Q0 134 16 78.0 team1-TFIDF_bnn_bnn
bam Q0 157 17 78.0 team1-TFIDF_bnn_bnn
bam Q0 2173 18 78.0 team1-TFIDF_bnn_bnn
bam Q0 414 19 78.0 team1-TFIDF_bnn_bnn
bam Q0 608 20 78.0 team1-TFIDF_bnn_bnn
bam Q0 2051 21 78.0 team1-TFIDF_bnn_bnn
bam Q0 462 22 78.0 team1-TFIDF_bnn_bnn
bam Q0 36 23 78.0 team1-TFIDF_bnn_bnn
bam Q0 2088 24 78.0 team1-TFIDF_bnn_bnn
bam Q0 2119 25 78.0 team1-TFIDF_bnn_bnn
bam Q0 1002 26 78.0 team1-TFIDF_bnn_bnn
bam Q0 237 27 78.0 team1-TFIDF_bnn_bnn
bam Q0 449 28 26.0 team1-TFIDF_bnn_bnn
bam Q0 2318 29 26.0 team1-TFIDF_bnn_bnn
bam Q0 678 30 26.0 team1-TFIDF_bnn_bnn
bam Q0 135 31 26.0 team1-TFIDF_bnn_bnn
bam Q0 2149 32 26.0 team1-TFIDF_bnn_bnn
bam Q0 402 33 26.0 team1-TFIDF_bnn_bnn
bam Q0 2163 34 26.0 team1-TFIDF_bnn_bnn
bam Q0 2316 35 26.0 team1-TFIDF_bnn_bnn
bam Q0 2223 36 26.0 team1-TFIDF_bnn_bnn
bam Q0 611 37 26.0 team1-TFIDF_bnn_bnn
bam Q0 401 38 26.0 team1-TFIDF_bnn_bnn
bam Q0 27 39 26.0 team1-TFIDF_bnn_bnn
bam Q0 525 40 26.0 team1-TFIDF_bnn_bnn
sequencing Q0 449 0 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 191 1 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2119 2 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 316 3 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 844 4 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 375 5 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 989 6 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2293 7 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2028 8 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2036 9 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 372 10 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 174 11 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 687 12 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 242 13 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 908 14 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 361 15 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 351 16 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2216 17 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 693 18 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 462 19 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 422 20 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2081 21 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 438 22 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 418 23 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2361 24 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 98 25 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 637 26 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2051 27 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2068 28 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2338 29 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 278 30 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 732 31 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 970 32 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 807 33 82.0 team1-TFIDF_bnn_bnn
sequencing Q0 2065 34 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 327 35 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 36 36 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 518 37 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 97 38 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 899 39 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 672 40 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 294 41 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 296 42 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 414 43 22.0 team1-TFIDF_bnn_bnn
sequencing Q0 2202 44 22.0 team1-TFIDF_bnn_bnn
mappability Q0 716 0 4.0 team1-TFIDF_bnn_bnn
mappability Q0 2293 1 2.0 team1-TFIDF_bnn_bnn
qc Q0 2065 0 14.0 team1-TFIDF_bnn_bnn
qc Q0 317 1 14.0 team1-TFIDF_bnn_bnn
qc Q0 2310 2 14.0 team1-TFIDF_bnn_bnn
qc Q0 92 3 14.0 team1-TFIDF_bnn_bnn
qc Q0 458 4 14.0 team1-TFIDF_bnn_bnn
qc Q0 253 5 14.0 team1-TFIDF_bnn_bnn
qc Q0 327 6 2.0 team1-TFIDF_bnn_bnn
trim Q0 228 0 4.0 team1-TFIDF_bnn_bnn
trim Q0 2119 1 4.0 team1-TFIDF_bnn_bnn
imputation Q0 336 0 4.0 team1-TFIDF_bnn_bnn
imputation Q0 317 1 4.0 team1-TFIDF_bnn_bnn
rpkm Q0 66 0 2.0 team1-TFIDF_bnn_bnn
scf Q0 692 0 2.0 team1-TFIDF_bnn_bnn
positive selection Q0 628 0 10.0 team1-TFIDF_bnn_bnn
positive selection Q0 761 1 10.0 team1-TFIDF_bnn_bnn
positive selection Q0 989 2 10.0 team1-TFIDF_bnn_bnn
positive selection Q0 798 3 10.0 team1-TFIDF_bnn_bnn
positive selection Q0 716 4 4.0 team1-TFIDF_bnn_bnn
positive selection Q0 62 5 4.0 team1-TFIDF_bnn_bnn
api Q0 500 0 16.0 team1-TFIDF_bnn_bnn
api Q0 892 1 16.0 team1-TFIDF_bnn_bnn
api Q0 1007 2 16.0 team1-TFIDF_bnn_bnn
api Q0 2062 3 16.0 team1-TFIDF_bnn_bnn
api Q0 829 4 16.0 team1-TFIDF_bnn_bnn
api Q0 731 5 16.0 team1-TFIDF_bnn_bnn
api Q0 933 6 4.0 team1-TFIDF_bnn_bnn
api Q0 623 7 4.0 team1-TFIDF_bnn_bnn
filtering Q0 769 0 28.0 team1-TFIDF_bnn_bnn
filtering Q0 194 1 28.0 team1-TFIDF_bnn_bnn
filtering Q0 508 2 28.0 team1-TFIDF_bnn_bnn
filtering Q0 486 3 28.0 team1-TFIDF_bnn_bnn
filtering Q0 1014 4 28.0 team1-TFIDF_bnn_bnn
filtering Q0 372 5 28.0 team1-TFIDF_bnn_bnn
filtering Q0 110 6 28.0 team1-TFIDF_bnn_bnn
filtering Q0 627 7 28.0 team1-TFIDF_bnn_bnn
filtering Q0 943 8 28.0 team1-TFIDF_bnn_bnn
filtering Q0 2054 9 28.0 team1-TFIDF_bnn_bnn
filtering Q0 951 10 28.0 team1-TFIDF_bnn_bnn
filtering Q0 264 11 28.0 team1-TFIDF_bnn_bnn
filtering Q0 2149 12 28.0 team1-TFIDF_bnn_bnn
filtering Q0 2131 13 6.0 team1-TFIDF_bnn_bnn
filtering Q0 237 14 6.0 team1-TFIDF_bnn_bnn
filtering Q0 317 15 6.0 team1-TFIDF_bnn_bnn
reactome Q0 230 0 4.0 team1-TFIDF_bnn_bnn
reactome Q0 1007 1 4.0 team1-TFIDF_bnn_bnn
adapter Q0 951 0 8.0 team1-TFIDF_bnn_bnn
adapter Q0 2119 1 8.0 team1-TFIDF_bnn_bnn
adapter Q0 2215 2 8.0 team1-TFIDF_bnn_bnn
adapter Q0 297 3 2.0 team1-TFIDF_bnn_bnn
bowtie2 Q0 945 0 10.0 team1-TFIDF_bnn_bnn
bowtie2 Q0 2202 1 10.0 team1-TFIDF_bnn_bnn
bowtie2 Q0 2054 2 10.0 team1-TFIDF_bnn_bnn
bowtie2 Q0 308 3 10.0 team1-TFIDF_bnn_bnn
bowtie2 Q0 322 4 2.0 team1-TFIDF_bnn_bnn
amova Q0 583 0 2.0 team1-TFIDF_bnn_bnn
radseq Q0 724 0 2.0 team1-TFIDF_bnn_bnn
quality control Q0 1 0 50.0 team1-TFIDF_bnn_bnn
quality control Q0 321 1 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2202 2 50.0 team1-TFIDF_bnn_bnn
quality control Q0 242 3 50.0 team1-TFIDF_bnn_bnn
quality control Q0 882 4 50.0 team1-TFIDF_bnn_bnn
quality control Q0 692 5 50.0 team1-TFIDF_bnn_bnn
quality control Q0 951 6 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2054 7 50.0 team1-TFIDF_bnn_bnn
quality control Q0 989 8 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2131 9 50.0 team1-TFIDF_bnn_bnn
quality control Q0 97 10 50.0 team1-TFIDF_bnn_bnn
quality control Q0 289 11 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2081 12 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2149 13 50.0 team1-TFIDF_bnn_bnn
quality control Q0 2215 14 50.0 team1-TFIDF_bnn_bnn
quality control Q0 663 15 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2234 16 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2073 17 38.0 team1-TFIDF_bnn_bnn
quality control Q0 491 18 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2265 19 38.0 team1-TFIDF_bnn_bnn
quality control Q0 970 20 38.0 team1-TFIDF_bnn_bnn
quality control Q0 317 21 38.0 team1-TFIDF_bnn_bnn
quality control Q0 708 22 38.0 team1-TFIDF_bnn_bnn
quality control Q0 842 23 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2140 24 38.0 team1-TFIDF_bnn_bnn
quality control Q0 81 25 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2028 26 38.0 team1-TFIDF_bnn_bnn
quality control Q0 920 27 38.0 team1-TFIDF_bnn_bnn
quality control Q0 73 28 38.0 team1-TFIDF_bnn_bnn
quality control Q0 327 29 38.0 team1-TFIDF_bnn_bnn
quality control Q0 610 30 38.0 team1-TFIDF_bnn_bnn
quality control Q0 869 31 38.0 team1-TFIDF_bnn_bnn
quality control Q0 2324 32 38.0 team1-TFIDF_bnn_bnn
quality control Q0 664 33 38.0 team1-TFIDF_bnn_bnn
quality control Q0 168 34 14.0 team1-TFIDF_bnn_bnn
quality control Q0 885 35 14.0 team1-TFIDF_bnn_bnn
quality control Q0 899 36 14.0 team1-TFIDF_bnn_bnn
quality control Q0 36 37 14.0 team1-TFIDF_bnn_bnn
quality control Q0 350 38 14.0 team1-TFIDF_bnn_bnn
quality control Q0 2163 39 14.0 team1-TFIDF_bnn_bnn
quality control Q0 424 40 14.0 team1-TFIDF_bnn_bnn
preprocessing Q0 2048 0 4.0 team1-TFIDF_bnn_bnn
preprocessing Q0 2119 1 4.0 team1-TFIDF_bnn_bnn
documentation Q0 161 0 24.0 team1-TFIDF_bnn_bnn
documentation Q0 157 1 24.0 team1-TFIDF_bnn_bnn
documentation Q0 956 2 24.0 team1-TFIDF_bnn_bnn
documentation Q0 251 3 24.0 team1-TFIDF_bnn_bnn
documentation Q0 513 4 24.0 team1-TFIDF_bnn_bnn
documentation Q0 884 5 24.0 team1-TFIDF_bnn_bnn
documentation Q0 2265 6 24.0 team1-TFIDF_bnn_bnn
documentation Q0 73 7 24.0 team1-TFIDF_bnn_bnn
documentation Q0 2165 8 24.0 team1-TFIDF_bnn_bnn
documentation Q0 266 9 24.0 team1-TFIDF_bnn_bnn
documentation Q0 561 10 24.0 team1-TFIDF_bnn_bnn
documentation Q0 2170 11 2.0 team1-TFIDF_bnn_bnn
rvtests Q0 627 0 2.0 team1-TFIDF_bnn_bnn
genome browser Q0 1 0 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 120 1 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 774 2 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 527 3 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 288 4 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 442 5 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 316 6 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 702 7 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 418 8 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 449 9 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 195 10 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 709 11 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 404 12 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 807 13 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 328 14 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 462 15 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 604 16 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 351 17 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 135 18 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 27 19 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 608 20 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 736 21 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 817 22 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 481 23 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 107 24 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 796 25 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 438 26 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 628 27 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 375 28 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 285 29 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 568 30 166.0 team1-TFIDF_bnn_bnn
genome browser Q0 2081 31 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 901 32 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 2274 33 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 97 34 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 303 35 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 168 36 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 990 37 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 5 38 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 174 39 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 2067 40 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 540 41 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 785 42 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 1001 43 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 821 44 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 518 45 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 318 46 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 36 47 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 70 48 52.0 team1-TFIDF_bnn_bnn
genome browser Q0 2216 49 52.0 team1-TFIDF_bnn_bnn
obitools Q0 150 0 2.0 team1-TFIDF_bnn_bnn
docking Q0 12 0 2.0 team1-TFIDF_bnn_bnn
metagenome Q0 306 0 6.0 team1-TFIDF_bnn_bnn
metagenome Q0 951 1 4.0 team1-TFIDF_bnn_bnn
metagenome Q0 2194 2 4.0 team1-TFIDF_bnn_bnn
unsupervised Q0 395 0 2.0 team1-TFIDF_bnn_bnn
10x Q0 2356 0 8.0 team1-TFIDF_bnn_bnn
10x Q0 329 1 8.0 team1-TFIDF_bnn_bnn
10x Q0 693 2 8.0 team1-TFIDF_bnn_bnn
10x Q0 771 3 4.0 team1-TFIDF_bnn_bnn
10x Q0 779 4 4.0 team1-TFIDF_bnn_bnn
snakemake Q0 491 0 6.0 team1-TFIDF_bnn_bnn
snakemake Q0 909 1 6.0 team1-TFIDF_bnn_bnn
snakemake Q0 2090 2 2.0 team1-TFIDF_bnn_bnn
exac Q0 2289 0 8.0 team1-TFIDF_bnn_bnn
exac Q0 842 1 8.0 team1-TFIDF_bnn_bnn
exac Q0 73 2 8.0 team1-TFIDF_bnn_bnn
exac Q0 933 3 8.0 team1-TFIDF_bnn_bnn
isoform Q0 595 0 4.0 team1-TFIDF_bnn_bnn
isoform Q0 2036 1 4.0 team1-TFIDF_bnn_bnn
biomart Q0 741 0 10.0 team1-TFIDF_bnn_bnn
biomart Q0 118 1 10.0 team1-TFIDF_bnn_bnn
biomart Q0 939 2 6.0 team1-TFIDF_bnn_bnn
biomart Q0 2300 3 6.0 team1-TFIDF_bnn_bnn
biomart Q0 2384 4 6.0 team1-TFIDF_bnn_bnn
schema Q0 565 0 4.0 team1-TFIDF_bnn_bnn
schema Q0 196 1 2.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 901 0 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 702 1 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 654 2 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2341 3 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 168 4 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 361 5 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 336 6 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 303 7 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 945 8 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2259 9 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2289 10 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2373 11 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 540 12 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 990 13 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 525 14 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 736 15 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 481 16 36.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 251 17 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2186 18 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 886 19 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 818 20 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 453 21 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 695 22 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 134 23 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2059 24 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2101 25 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 2128 26 26.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 626 27 2.0 team1-TFIDF_bnn_bnn
1000 genomes Q0 994 28 2.0 team1-TFIDF_bnn_bnn
differential expression Q0 2241 0 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 66 1 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2308 2 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 456 3 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 1018 4 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2298 5 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 278 6 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 886 7 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 153 8 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 584 9 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2329 10 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 779 11 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2356 12 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 372 13 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 51 14 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 29 15 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2234 16 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 703 17 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2346 18 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2088 19 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 194 20 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 524 21 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2282 22 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2375 23 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 687 24 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 21 25 72.0 team1-TFIDF_bnn_bnn
differential expression Q0 2140 26 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 2165 27 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 777 28 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 2310 29 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 909 30 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 774 31 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 559 32 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 2321 33 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 505 34 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 567 35 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 441 36 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 165 37 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 238 38 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 1019 39 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 857 40 26.0 team1-TFIDF_bnn_bnn
differential expression Q0 314 41 8.0 team1-TFIDF_bnn_bnn
networks Q0 194 0 6.0 team1-TFIDF_bnn_bnn
networks Q0 2059 1 6.0 team1-TFIDF_bnn_bnn
networks Q0 2310 2 2.0 team1-TFIDF_bnn_bnn
liftover Q0 2083 0 8.0 team1-TFIDF_bnn_bnn
liftover Q0 303 1 8.0 team1-TFIDF_bnn_bnn
liftover Q0 318 2 8.0 team1-TFIDF_bnn_bnn
liftover Q0 837 3 8.0 team1-TFIDF_bnn_bnn
fasta Q0 2049 0 74.0 team1-TFIDF_bnn_bnn
fasta Q0 702 1 74.0 team1-TFIDF_bnn_bnn
fasta Q0 765 2 74.0 team1-TFIDF_bnn_bnn
fasta Q0 2316 3 74.0 team1-TFIDF_bnn_bnn
fasta Q0 1019 4 74.0 team1-TFIDF_bnn_bnn
fasta Q0 604 5 74.0 team1-TFIDF_bnn_bnn
fasta Q0 628 6 74.0 team1-TFIDF_bnn_bnn
fasta Q0 375 7 74.0 team1-TFIDF_bnn_bnn
fasta Q0 954 8 74.0 team1-TFIDF_bnn_bnn
fasta Q0 561 9 74.0 team1-TFIDF_bnn_bnn
fasta Q0 928 10 74.0 team1-TFIDF_bnn_bnn
fasta Q0 892 11 74.0 team1-TFIDF_bnn_bnn
fasta Q0 802 12 74.0 team1-TFIDF_bnn_bnn
fasta Q0 2062 13 74.0 team1-TFIDF_bnn_bnn
fasta Q0 994 14 74.0 team1-TFIDF_bnn_bnn
fasta Q0 2149 15 74.0 team1-TFIDF_bnn_bnn
fasta Q0 553 16 74.0 team1-TFIDF_bnn_bnn
fasta Q0 388 17 74.0 team1-TFIDF_bnn_bnn
fasta Q0 81 18 74.0 team1-TFIDF_bnn_bnn
fasta Q0 943 19 74.0 team1-TFIDF_bnn_bnn
fasta Q0 972 20 74.0 team1-TFIDF_bnn_bnn
fasta Q0 979 21 74.0 team1-TFIDF_bnn_bnn
fasta Q0 2259 22 74.0 team1-TFIDF_bnn_bnn
fasta Q0 14 23 30.0 team1-TFIDF_bnn_bnn
fasta Q0 307 24 30.0 team1-TFIDF_bnn_bnn
fasta Q0 837 25 30.0 team1-TFIDF_bnn_bnn
fasta Q0 361 26 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2186 27 30.0 team1-TFIDF_bnn_bnn
fasta Q0 45 28 30.0 team1-TFIDF_bnn_bnn
fasta Q0 595 29 30.0 team1-TFIDF_bnn_bnn
fasta Q0 815 30 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2114 31 30.0 team1-TFIDF_bnn_bnn
fasta Q0 91 32 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2095 33 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2156 34 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2223 35 30.0 team1-TFIDF_bnn_bnn
fasta Q0 709 36 30.0 team1-TFIDF_bnn_bnn
fasta Q0 2128 37 30.0 team1-TFIDF_bnn_bnn
spark Q0 426 0 2.0 team1-TFIDF_bnn_bnn
proteins Q0 2049 0 38.0 team1-TFIDF_bnn_bnn
proteins Q0 703 1 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2241 2 38.0 team1-TFIDF_bnn_bnn
proteins Q0 731 3 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2343 4 38.0 team1-TFIDF_bnn_bnn
proteins Q0 282 5 38.0 team1-TFIDF_bnn_bnn
proteins Q0 1016 6 38.0 team1-TFIDF_bnn_bnn
proteins Q0 887 7 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2128 8 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2130 9 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2321 10 38.0 team1-TFIDF_bnn_bnn
proteins Q0 314 11 38.0 team1-TFIDF_bnn_bnn
proteins Q0 350 12 38.0 team1-TFIDF_bnn_bnn
proteins Q0 558 13 38.0 team1-TFIDF_bnn_bnn
proteins Q0 2324 14 38.0 team1-TFIDF_bnn_bnn
proteins Q0 584 15 38.0 team1-TFIDF_bnn_bnn
proteins Q0 677 16 38.0 team1-TFIDF_bnn_bnn
proteins Q0 553 17 4.0 team1-TFIDF_bnn_bnn
proteins Q0 2257 18 4.0 team1-TFIDF_bnn_bnn
assembly Q0 97 0 30.0 team1-TFIDF_bnn_bnn
assembly Q0 326 1 30.0 team1-TFIDF_bnn_bnn
assembly Q0 540 2 30.0 team1-TFIDF_bnn_bnn
assembly Q0 942 3 30.0 team1-TFIDF_bnn_bnn
assembly Q0 375 4 30.0 team1-TFIDF_bnn_bnn
assembly Q0 2204 5 30.0 team1-TFIDF_bnn_bnn
assembly Q0 73 6 30.0 team1-TFIDF_bnn_bnn
assembly Q0 752 7 30.0 team1-TFIDF_bnn_bnn
assembly Q0 361 8 30.0 team1-TFIDF_bnn_bnn
assembly Q0 885 9 30.0 team1-TFIDF_bnn_bnn
assembly Q0 46 10 30.0 team1-TFIDF_bnn_bnn
assembly Q0 2145 11 10.0 team1-TFIDF_bnn_bnn
assembly Q0 242 12 10.0 team1-TFIDF_bnn_bnn
assembly Q0 951 13 10.0 team1-TFIDF_bnn_bnn
assembly Q0 174 14 10.0 team1-TFIDF_bnn_bnn
assembly Q0 452 15 10.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 5 0 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 294 1 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 570 2 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 375 3 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 378 4 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 837 5 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 388 6 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 70 7 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 45 8 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 303 9 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 159 10 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 935 11 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 692 12 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 815 13 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 847 14 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 950 15 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 595 16 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 703 17 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 705 18 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 452 19 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 289 20 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 561 21 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 817 22 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 343 23 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 722 24 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 91 25 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 732 26 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 225 27 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 818 28 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 228 29 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 741 30 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 802 31 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 107 32 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 620 33 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 765 34 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 882 35 146.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 92 36 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 372 37 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 2073 38 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 62 39 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 318 40 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 125 41 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 2199 42 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 135 43 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 654 44 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 143 45 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 583 46 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 149 47 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 1012 48 122.0 team1-TFIDF_bnn_bnn
sequence analysis Q0 1014 49 122.0 team1-TFIDF_bnn_bnn
public databases Q0 2113 0 34.0 team1-TFIDF_bnn_bnn
public databases Q0 633 1 34.0 team1-TFIDF_bnn_bnn
public databases Q0 777 2 34.0 team1-TFIDF_bnn_bnn
public databases Q0 673 3 34.0 team1-TFIDF_bnn_bnn
public databases Q0 2156 4 34.0 team1-TFIDF_bnn_bnn
public databases Q0 2224 5 34.0 team1-TFIDF_bnn_bnn
public databases Q0 877 6 34.0 team1-TFIDF_bnn_bnn
public databases Q0 802 7 34.0 team1-TFIDF_bnn_bnn
public databases Q0 815 8 34.0 team1-TFIDF_bnn_bnn
public databases Q0 567 9 34.0 team1-TFIDF_bnn_bnn
public databases Q0 2194 10 34.0 team1-TFIDF_bnn_bnn
public databases Q0 168 11 34.0 team1-TFIDF_bnn_bnn
public databases Q0 486 12 34.0 team1-TFIDF_bnn_bnn
public databases Q0 548 13 34.0 team1-TFIDF_bnn_bnn
public databases Q0 887 14 34.0 team1-TFIDF_bnn_bnn
public databases Q0 21 15 34.0 team1-TFIDF_bnn_bnn
public databases Q0 2289 16 10.0 team1-TFIDF_bnn_bnn
public databases Q0 418 17 10.0 team1-TFIDF_bnn_bnn
public databases Q0 452 18 10.0 team1-TFIDF_bnn_bnn
public databases Q0 488 19 6.0 team1-TFIDF_bnn_bnn
public databases Q0 933 20 6.0 team1-TFIDF_bnn_bnn
public databases Q0 2153 21 6.0 team1-TFIDF_bnn_bnn
public databases Q0 842 22 6.0 team1-TFIDF_bnn_bnn
public databases Q0 388 23 6.0 team1-TFIDF_bnn_bnn
public databases Q0 990 24 6.0 team1-TFIDF_bnn_bnn
variant calling Q0 2306 0 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 264 1 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 949 2 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 317 3 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 336 4 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 722 5 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 842 6 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 481 7 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 908 8 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 2275 9 44.0 team1-TFIDF_bnn_bnn
variant calling Q0 161 10 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 458 11 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 909 12 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 120 13 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 705 14 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 73 15 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 191 16 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 974 17 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 462 18 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 407 19 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 294 20 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 672 21 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 452 22 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 2149 23 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 899 24 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 98 25 38.0 team1-TFIDF_bnn_bnn
variant calling Q0 271 26 16.0 team1-TFIDF_bnn_bnn
variant calling Q0 654 27 16.0 team1-TFIDF_bnn_bnn
variant calling Q0 195 28 16.0 team1-TFIDF_bnn_bnn
variant calling Q0 587 29 16.0 team1-TFIDF_bnn_bnn
variant calling Q0 321 30 12.0 team1-TFIDF_bnn_bnn
variant calling Q0 449 31 12.0 team1-TFIDF_bnn_bnn
variant calling Q0 253 32 12.0 team1-TFIDF_bnn_bnn
variant calling Q0 329 33 12.0 team1-TFIDF_bnn_bnn
variant calling Q0 157 34 12.0 team1-TFIDF_bnn_bnn
variant calling Q0 2377 35 12.0 team1-TFIDF_bnn_bnn
cell line Q0 2241 0 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2177 1 60.0 team1-TFIDF_bnn_bnn
cell line Q0 62 2 60.0 team1-TFIDF_bnn_bnn
cell line Q0 708 3 60.0 team1-TFIDF_bnn_bnn
cell line Q0 627 4 60.0 team1-TFIDF_bnn_bnn
cell line Q0 954 5 60.0 team1-TFIDF_bnn_bnn
cell line Q0 908 6 60.0 team1-TFIDF_bnn_bnn
cell line Q0 500 7 60.0 team1-TFIDF_bnn_bnn
cell line Q0 887 8 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2164 9 60.0 team1-TFIDF_bnn_bnn
cell line Q0 195 10 60.0 team1-TFIDF_bnn_bnn
cell line Q0 722 11 60.0 team1-TFIDF_bnn_bnn
cell line Q0 694 12 60.0 team1-TFIDF_bnn_bnn
cell line Q0 838 13 60.0 team1-TFIDF_bnn_bnn
cell line Q0 91 14 60.0 team1-TFIDF_bnn_bnn
cell line Q0 411 15 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2242 16 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2051 17 60.0 team1-TFIDF_bnn_bnn
cell line Q0 935 18 60.0 team1-TFIDF_bnn_bnn
cell line Q0 361 19 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2092 20 60.0 team1-TFIDF_bnn_bnn
cell line Q0 388 21 60.0 team1-TFIDF_bnn_bnn
cell line Q0 266 22 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2090 23 60.0 team1-TFIDF_bnn_bnn
cell line Q0 2186 24 60.0 team1-TFIDF_bnn_bnn
cell line Q0 306 25 44.0 team1-TFIDF_bnn_bnn
cell line Q0 395 26 44.0 team1-TFIDF_bnn_bnn
cell line Q0 779 27 44.0 team1-TFIDF_bnn_bnn
cell line Q0 441 28 44.0 team1-TFIDF_bnn_bnn
cell line Q0 765 29 44.0 team1-TFIDF_bnn_bnn
cell line Q0 2356 30 44.0 team1-TFIDF_bnn_bnn
cell line Q0 2310 31 44.0 team1-TFIDF_bnn_bnn
cell line Q0 750 32 44.0 team1-TFIDF_bnn_bnn
cell line Q0 584 33 44.0 team1-TFIDF_bnn_bnn
cell line Q0 29 34 44.0 team1-TFIDF_bnn_bnn
cell line Q0 46 35 44.0 team1-TFIDF_bnn_bnn
cell line Q0 249 36 20.0 team1-TFIDF_bnn_bnn
cell line Q0 703 37 20.0 team1-TFIDF_bnn_bnn
cell line Q0 693 38 20.0 team1-TFIDF_bnn_bnn
cell line Q0 2109 39 20.0 team1-TFIDF_bnn_bnn
cell line Q0 914 40 20.0 team1-TFIDF_bnn_bnn
cell line Q0 771 41 20.0 team1-TFIDF_bnn_bnn
cell line Q0 434 42 20.0 team1-TFIDF_bnn_bnn
cell line Q0 777 43 10.0 team1-TFIDF_bnn_bnn
cell line Q0 1014 44 10.0 team1-TFIDF_bnn_bnn
cell line Q0 278 45 10.0 team1-TFIDF_bnn_bnn
cell line Q0 453 46 10.0 team1-TFIDF_bnn_bnn
cell line Q0 2078 47 10.0 team1-TFIDF_bnn_bnn
fastq Q0 2051 0 52.0 team1-TFIDF_bnn_bnn
fastq Q0 2119 1 52.0 team1-TFIDF_bnn_bnn
fastq Q0 411 2 52.0 team1-TFIDF_bnn_bnn
fastq Q0 1002 3 52.0 team1-TFIDF_bnn_bnn
fastq Q0 414 4 52.0 team1-TFIDF_bnn_bnn
fastq Q0 561 5 52.0 team1-TFIDF_bnn_bnn
fastq Q0 242 6 52.0 team1-TFIDF_bnn_bnn
fastq Q0 98 7 52.0 team1-TFIDF_bnn_bnn
fastq Q0 372 8 52.0 team1-TFIDF_bnn_bnn
fastq Q0 951 9 52.0 team1-TFIDF_bnn_bnn
fastq Q0 452 10 52.0 team1-TFIDF_bnn_bnn
fastq Q0 2361 11 52.0 team1-TFIDF_bnn_bnn
fastq Q0 150 12 52.0 team1-TFIDF_bnn_bnn
fastq Q0 2088 13 52.0 team1-TFIDF_bnn_bnn
fastq Q0 807 14 24.0 team1-TFIDF_bnn_bnn
fastq Q0 14 15 24.0 team1-TFIDF_bnn_bnn
fastq Q0 882 16 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2335 17 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2316 18 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2174 19 24.0 team1-TFIDF_bnn_bnn
fastq Q0 361 20 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2306 21 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2149 22 24.0 team1-TFIDF_bnn_bnn
fastq Q0 2230 23 24.0 team1-TFIDF_bnn_bnn
fastq Q0 935 24 24.0 team1-TFIDF_bnn_bnn
fastq Q0 892 25 24.0 team1-TFIDF_bnn_bnn
codon models Q0 70 0 18.0 team1-TFIDF_bnn_bnn
codon models Q0 782 1 18.0 team1-TFIDF_bnn_bnn
codon models Q0 350 2 18.0 team1-TFIDF_bnn_bnn
codon models Q0 378 3 18.0 team1-TFIDF_bnn_bnn
codon models Q0 2140 4 18.0 team1-TFIDF_bnn_bnn
codon models Q0 89 5 18.0 team1-TFIDF_bnn_bnn
codon models Q0 125 6 18.0 team1-TFIDF_bnn_bnn
codon models Q0 2259 7 10.0 team1-TFIDF_bnn_bnn
codon models Q0 732 8 10.0 team1-TFIDF_bnn_bnn
codon models Q0 2300 9 10.0 team1-TFIDF_bnn_bnn
codon models Q0 877 10 6.0 team1-TFIDF_bnn_bnn
codon models Q0 57 11 6.0 team1-TFIDF_bnn_bnn
codon models Q0 159 12 6.0 team1-TFIDF_bnn_bnn
codon models Q0 997 13 2.0 team1-TFIDF_bnn_bnn
annotation Q0 2088 0 26.0 team1-TFIDF_bnn_bnn
annotation Q0 2106 1 26.0 team1-TFIDF_bnn_bnn
annotation Q0 2029 2 26.0 team1-TFIDF_bnn_bnn
annotation Q0 664 3 26.0 team1-TFIDF_bnn_bnn
annotation Q0 2068 4 26.0 team1-TFIDF_bnn_bnn
annotation Q0 462 5 26.0 team1-TFIDF_bnn_bnn
annotation Q0 2101 6 26.0 team1-TFIDF_bnn_bnn
annotation Q0 314 7 26.0 team1-TFIDF_bnn_bnn
annotation Q0 969 8 14.0 team1-TFIDF_bnn_bnn
annotation Q0 21 9 14.0 team1-TFIDF_bnn_bnn
annotation Q0 565 10 14.0 team1-TFIDF_bnn_bnn
annotation Q0 2343 11 14.0 team1-TFIDF_bnn_bnn
annotation Q0 2036 12 14.0 team1-TFIDF_bnn_bnn
annotation Q0 1012 13 14.0 team1-TFIDF_bnn_bnn
annotation Q0 70 14 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 2145 0 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 869 1 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 2361 2 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 568 3 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 583 4 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 150 5 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 452 6 14.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 73 7 4.0 team1-TFIDF_bnn_bnn
molecular genetics Q0 2352 8 4.0 team1-TFIDF_bnn_bnn
platypus Q0 73 0 2.0 team1-TFIDF_bnn_bnn
centromere Q0 2293 0 2.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 135 0 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 524 1 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 125 2 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 149 3 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 939 4 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 842 5 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 1014 6 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 945 7 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2131 8 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 1012 9 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 372 10 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2163 11 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 627 12 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2097 13 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 731 14 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 92 15 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2098 16 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2140 17 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 609 18 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2199 19 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 52 20 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 997 21 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2149 22 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 230 23 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 949 24 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 654 25 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2073 26 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 954 27 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2028 28 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 242 29 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 540 30 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 62 31 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 318 32 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 584 33 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 761 34 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 143 35 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 702 36 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 194 37 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 583 38 122.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 771 39 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 112 40 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2361 41 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 664 42 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 103 43 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 994 44 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 751 45 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2165 46 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2346 47 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2321 48 46.0 team1-TFIDF_bnn_bnn
covariate analysis Q0 2282 49 46.0 team1-TFIDF_bnn_bnn
star Q0 280 0 6.0 team1-TFIDF_bnn_bnn
star Q0 2140 1 6.0 team1-TFIDF_bnn_bnn
star Q0 518 2 2.0 team1-TFIDF_bnn_bnn
abi Q0 692 0 2.0 team1-TFIDF_bnn_bnn
machine learning Q0 628 0 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 676 1 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 143 2 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 702 3 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 2092 4 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 191 5 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 2073 6 14.0 team1-TFIDF_bnn_bnn
machine learning Q0 716 7 4.0 team1-TFIDF_bnn_bnn
blast Q0 288 0 40.0 team1-TFIDF_bnn_bnn
blast Q0 798 1 40.0 team1-TFIDF_bnn_bnn
blast Q0 796 2 40.0 team1-TFIDF_bnn_bnn
blast Q0 960 3 40.0 team1-TFIDF_bnn_bnn
blast Q0 802 4 40.0 team1-TFIDF_bnn_bnn
blast Q0 970 5 40.0 team1-TFIDF_bnn_bnn
blast Q0 2194 6 40.0 team1-TFIDF_bnn_bnn
blast Q0 2130 7 40.0 team1-TFIDF_bnn_bnn
blast Q0 646 8 40.0 team1-TFIDF_bnn_bnn
blast Q0 817 9 40.0 team1-TFIDF_bnn_bnn
blast Q0 110 10 40.0 team1-TFIDF_bnn_bnn
blast Q0 815 11 40.0 team1-TFIDF_bnn_bnn
blast Q0 2049 12 40.0 team1-TFIDF_bnn_bnn
blast Q0 847 13 40.0 team1-TFIDF_bnn_bnn
blast Q0 650 14 40.0 team1-TFIDF_bnn_bnn
blast Q0 2092 15 12.0 team1-TFIDF_bnn_bnn
blast Q0 887 16 12.0 team1-TFIDF_bnn_bnn
blast Q0 424 17 12.0 team1-TFIDF_bnn_bnn
blast Q0 818 18 12.0 team1-TFIDF_bnn_bnn
blast Q0 2164 19 12.0 team1-TFIDF_bnn_bnn
blast Q0 2257 20 12.0 team1-TFIDF_bnn_bnn
consensus Q0 2065 0 12.0 team1-TFIDF_bnn_bnn
consensus Q0 285 1 12.0 team1-TFIDF_bnn_bnn
consensus Q0 901 2 12.0 team1-TFIDF_bnn_bnn
consensus Q0 2241 3 12.0 team1-TFIDF_bnn_bnn
consensus Q0 242 4 12.0 team1-TFIDF_bnn_bnn
consensus Q0 452 5 2.0 team1-TFIDF_bnn_bnn
busted Q0 62 0 2.0 team1-TFIDF_bnn_bnn
r Q0 2051 0 96.0 team1-TFIDF_bnn_bnn
r Q0 639 1 96.0 team1-TFIDF_bnn_bnn
r Q0 264 2 96.0 team1-TFIDF_bnn_bnn
r Q0 779 3 96.0 team1-TFIDF_bnn_bnn
r Q0 2300 4 96.0 team1-TFIDF_bnn_bnn
r Q0 1016 5 96.0 team1-TFIDF_bnn_bnn
r Q0 2165 6 96.0 team1-TFIDF_bnn_bnn
r Q0 2164 7 96.0 team1-TFIDF_bnn_bnn
r Q0 628 8 96.0 team1-TFIDF_bnn_bnn
r Q0 150 9 96.0 team1-TFIDF_bnn_bnn
r Q0 1007 10 96.0 team1-TFIDF_bnn_bnn
r Q0 751 11 96.0 team1-TFIDF_bnn_bnn
r Q0 687 12 96.0 team1-TFIDF_bnn_bnn
r Q0 869 13 96.0 team1-TFIDF_bnn_bnn
r Q0 741 14 96.0 team1-TFIDF_bnn_bnn
r Q0 2274 15 96.0 team1-TFIDF_bnn_bnn
r Q0 608 16 96.0 team1-TFIDF_bnn_bnn
r Q0 731 17 96.0 team1-TFIDF_bnn_bnn
r Q0 2259 18 96.0 team1-TFIDF_bnn_bnn
r Q0 982 19 96.0 team1-TFIDF_bnn_bnn
r Q0 307 20 96.0 team1-TFIDF_bnn_bnn
r Q0 847 21 96.0 team1-TFIDF_bnn_bnn
r Q0 344 22 96.0 team1-TFIDF_bnn_bnn
r Q0 663 23 96.0 team1-TFIDF_bnn_bnn
r Q0 695 24 96.0 team1-TFIDF_bnn_bnn
r Q0 583 25 96.0 team1-TFIDF_bnn_bnn
r Q0 2234 26 96.0 team1-TFIDF_bnn_bnn
r Q0 2302 27 96.0 team1-TFIDF_bnn_bnn
r Q0 2114 28 96.0 team1-TFIDF_bnn_bnn
r Q0 578 29 96.0 team1-TFIDF_bnn_bnn
r Q0 2111 30 96.0 team1-TFIDF_bnn_bnn
r Q0 702 31 96.0 team1-TFIDF_bnn_bnn
r Q0 908 32 96.0 team1-TFIDF_bnn_bnn
r Q0 956 33 96.0 team1-TFIDF_bnn_bnn
r Q0 2152 34 96.0 team1-TFIDF_bnn_bnn
r Q0 920 35 96.0 team1-TFIDF_bnn_bnn
r Q0 2186 36 96.0 team1-TFIDF_bnn_bnn
r Q0 716 37 96.0 team1-TFIDF_bnn_bnn
r Q0 584 38 96.0 team1-TFIDF_bnn_bnn
r Q0 838 39 96.0 team1-TFIDF_bnn_bnn
r Q0 525 40 96.0 team1-TFIDF_bnn_bnn
r Q0 153 41 96.0 team1-TFIDF_bnn_bnn
r Q0 909 42 96.0 team1-TFIDF_bnn_bnn
r Q0 923 43 16.0 team1-TFIDF_bnn_bnn
r Q0 2173 44 16.0 team1-TFIDF_bnn_bnn
r Q0 2203 45 16.0 team1-TFIDF_bnn_bnn
r Q0 1010 46 16.0 team1-TFIDF_bnn_bnn
r Q0 66 47 16.0 team1-TFIDF_bnn_bnn
r Q0 456 48 16.0 team1-TFIDF_bnn_bnn
r Q0 282 49 16.0 team1-TFIDF_bnn_bnn
nlp Q0 2137 0 2.0 team1-TFIDF_bnn_bnn
personal genomics Q0 752 0 10.0 team1-TFIDF_bnn_bnn
personal genomics Q0 458 1 10.0 team1-TFIDF_bnn_bnn
personal genomics Q0 283 2 10.0 team1-TFIDF_bnn_bnn
personal genomics Q0 357 3 10.0 team1-TFIDF_bnn_bnn
personal genomics Q0 195 4 10.0 team1-TFIDF_bnn_bnn
personal genomics Q0 196 5 4.0 team1-TFIDF_bnn_bnn
personal genomics Q0 481 6 4.0 team1-TFIDF_bnn_bnn
personal genomics Q0 308 7 4.0 team1-TFIDF_bnn_bnn
personal genomics Q0 771 8 4.0 team1-TFIDF_bnn_bnn
pathway Q0 2321 0 18.0 team1-TFIDF_bnn_bnn
pathway Q0 584 1 18.0 team1-TFIDF_bnn_bnn
pathway Q0 623 2 18.0 team1-TFIDF_bnn_bnn
pathway Q0 2234 3 18.0 team1-TFIDF_bnn_bnn
pathway Q0 2059 4 18.0 team1-TFIDF_bnn_bnn
pathway Q0 568 5 18.0 team1-TFIDF_bnn_bnn
pathway Q0 1007 6 6.0 team1-TFIDF_bnn_bnn
pathway Q0 567 7 6.0 team1-TFIDF_bnn_bnn
pathway Q0 844 8 6.0 team1-TFIDF_bnn_bnn
albacore Q0 2174 0 4.0 team1-TFIDF_bnn_bnn
albacore Q0 745 1 2.0 team1-TFIDF_bnn_bnn
transposable elements Q0 146 0 4.0 team1-TFIDF_bnn_bnn
transposable elements Q0 343 1 4.0 team1-TFIDF_bnn_bnn
bed Q0 288 0 34.0 team1-TFIDF_bnn_bnn
bed Q0 608 1 34.0 team1-TFIDF_bnn_bnn
bed Q0 427 2 34.0 team1-TFIDF_bnn_bnn
bed Q0 2275 3 34.0 team1-TFIDF_bnn_bnn
bed Q0 531 4 34.0 team1-TFIDF_bnn_bnn
bed Q0 661 5 34.0 team1-TFIDF_bnn_bnn
bed Q0 2036 6 34.0 team1-TFIDF_bnn_bnn
bed Q0 837 7 34.0 team1-TFIDF_bnn_bnn
bed Q0 565 8 34.0 team1-TFIDF_bnn_bnn
bed Q0 27 9 34.0 team1-TFIDF_bnn_bnn
bed Q0 2083 10 14.0 team1-TFIDF_bnn_bnn
bed Q0 91 11 14.0 team1-TFIDF_bnn_bnn
bed Q0 134 12 14.0 team1-TFIDF_bnn_bnn
bed Q0 2265 13 14.0 team1-TFIDF_bnn_bnn
bed Q0 895 14 14.0 team1-TFIDF_bnn_bnn
bed Q0 2318 15 14.0 team1-TFIDF_bnn_bnn
bed Q0 2242 16 14.0 team1-TFIDF_bnn_bnn
encode Q0 673 0 8.0 team1-TFIDF_bnn_bnn
encode Q0 458 1 8.0 team1-TFIDF_bnn_bnn
encode Q0 2051 2 8.0 team1-TFIDF_bnn_bnn
encode Q0 249 3 2.0 team1-TFIDF_bnn_bnn
visualization Q0 565 0 4.0 team1-TFIDF_bnn_bnn
visualization Q0 663 1 4.0 team1-TFIDF_bnn_bnn
visualization Q0 2117 2 4.0 team1-TFIDF_bnn_bnn
annovar Q0 98 0 4.0 team1-TFIDF_bnn_bnn
annovar Q0 2224 1 2.0 team1-TFIDF_bnn_bnn
canu Q0 2145 0 6.0 team1-TFIDF_bnn_bnn
canu Q0 242 1 6.0 team1-TFIDF_bnn_bnn
canu Q0 2367 2 2.0 team1-TFIDF_bnn_bnn
protein structure Q0 2179 0 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 388 1 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2059 2 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2241 3 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 196 4 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2341 5 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2378 6 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 553 7 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2349 8 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 982 9 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 994 10 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 997 11 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2186 12 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 818 13 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 107 14 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 314 15 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 378 16 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 125 17 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 570 18 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 2237 19 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 960 20 82.0 team1-TFIDF_bnn_bnn
protein structure Q0 1007 21 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 567 22 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 282 23 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 798 24 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 2343 25 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 972 26 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 2128 27 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 2130 28 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 653 29 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 950 30 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 558 31 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 844 32 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 350 33 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 2049 34 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 924 35 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 2111 36 34.0 team1-TFIDF_bnn_bnn
protein structure Q0 837 37 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 909 38 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 2177 39 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 452 40 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 375 41 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 914 42 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 242 43 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 869 44 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 110 45 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 2246 46 32.0 team1-TFIDF_bnn_bnn
protein structure Q0 2339 47 14.0 team1-TFIDF_bnn_bnn
protein structure Q0 650 48 14.0 team1-TFIDF_bnn_bnn
protein structure Q0 528 49 14.0 team1-TFIDF_bnn_bnn
atc Q0 388 0 6.0 team1-TFIDF_bnn_bnn
atc Q0 2390 1 6.0 team1-TFIDF_bnn_bnn
atc Q0 9 2 2.0 team1-TFIDF_bnn_bnn
gene ontology Q0 516 0 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 909 1 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 161 2 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 673 3 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 62 4 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 637 5 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 378 6 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 193 7 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 118 8 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 66 9 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 372 10 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 194 11 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 70 12 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 456 13 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 2062 14 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 299 15 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 997 16 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 869 17 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 994 18 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 333 19 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 939 20 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 849 21 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 687 22 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 779 23 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 149 24 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 51 25 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 481 26 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 565 27 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 693 28 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 747 29 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 153 30 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 57 31 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 367 32 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 1012 33 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 285 34 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 441 35 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 1018 36 150.0 team1-TFIDF_bnn_bnn
gene ontology Q0 2300 37 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 2114 38 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 857 39 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 844 40 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 238 41 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 595 42 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 314 43 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 2323 44 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 559 45 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 488 46 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 567 47 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 2310 48 52.0 team1-TFIDF_bnn_bnn
gene ontology Q0 548 49 52.0 team1-TFIDF_bnn_bnn
fast5 Q0 452 0 6.0 team1-TFIDF_bnn_bnn
fast5 Q0 745 1 6.0 team1-TFIDF_bnn_bnn
fast5 Q0 2306 2 2.0 team1-TFIDF_bnn_bnn
pfam Q0 972 0 2.0 team1-TFIDF_bnn_bnn
trimming Q0 242 0 4.0 team1-TFIDF_bnn_bnn
trimming Q0 2215 1 4.0 team1-TFIDF_bnn_bnn
trimming Q0 2119 2 4.0 team1-TFIDF_bnn_bnn
rsem Q0 610 0 4.0 team1-TFIDF_bnn_bnn
rsem Q0 372 1 2.0 team1-TFIDF_bnn_bnn
barcode Q0 970 0 4.0 team1-TFIDF_bnn_bnn
barcode Q0 779 1 4.0 team1-TFIDF_bnn_bnn
barcode Q0 297 2 2.0 team1-TFIDF_bnn_bnn
ontology Q0 998 0 6.0 team1-TFIDF_bnn_bnn
ontology Q0 9 1 6.0 team1-TFIDF_bnn_bnn
ontology Q0 568 2 6.0 team1-TFIDF_bnn_bnn
homer Q0 516 0 2.0 team1-TFIDF_bnn_bnn
admixture Q0 481 0 4.0 team1-TFIDF_bnn_bnn
admixture Q0 351 1 4.0 team1-TFIDF_bnn_bnn
data download Q0 9 0 266.0 team1-TFIDF_bnn_bnn
data download Q0 395 1 266.0 team1-TFIDF_bnn_bnn
data download Q0 282 2 266.0 team1-TFIDF_bnn_bnn
data download Q0 308 3 266.0 team1-TFIDF_bnn_bnn
data download Q0 481 4 266.0 team1-TFIDF_bnn_bnn
data download Q0 609 5 266.0 team1-TFIDF_bnn_bnn
data download Q0 610 6 266.0 team1-TFIDF_bnn_bnn
data download Q0 565 7 266.0 team1-TFIDF_bnn_bnn
data download Q0 103 8 266.0 team1-TFIDF_bnn_bnn
data download Q0 232 9 266.0 team1-TFIDF_bnn_bnn
data download Q0 488 10 266.0 team1-TFIDF_bnn_bnn
data download Q0 283 11 266.0 team1-TFIDF_bnn_bnn
data download Q0 567 12 266.0 team1-TFIDF_bnn_bnn
data download Q0 57 13 266.0 team1-TFIDF_bnn_bnn
data download Q0 242 14 266.0 team1-TFIDF_bnn_bnn
data download Q0 29 15 266.0 team1-TFIDF_bnn_bnn
data download Q0 66 16 266.0 team1-TFIDF_bnn_bnn
data download Q0 626 17 266.0 team1-TFIDF_bnn_bnn
data download Q0 627 18 266.0 team1-TFIDF_bnn_bnn
data download Q0 372 19 266.0 team1-TFIDF_bnn_bnn
data download Q0 195 20 266.0 team1-TFIDF_bnn_bnn
data download Q0 196 21 266.0 team1-TFIDF_bnn_bnn
data download Q0 19 22 266.0 team1-TFIDF_bnn_bnn
data download Q0 418 23 266.0 team1-TFIDF_bnn_bnn
data download Q0 452 24 266.0 team1-TFIDF_bnn_bnn
data download Q0 294 25 266.0 team1-TFIDF_bnn_bnn
data download Q0 584 26 266.0 team1-TFIDF_bnn_bnn
data download Q0 73 27 266.0 team1-TFIDF_bnn_bnn
data download Q0 83 28 266.0 team1-TFIDF_bnn_bnn
data download Q0 343 29 266.0 team1-TFIDF_bnn_bnn
data download Q0 89 30 266.0 team1-TFIDF_bnn_bnn
data download Q0 92 31 266.0 team1-TFIDF_bnn_bnn
data download Q0 351 32 266.0 team1-TFIDF_bnn_bnn
data download Q0 458 33 78.0 team1-TFIDF_bnn_bnn
data download Q0 253 34 78.0 team1-TFIDF_bnn_bnn
data download Q0 120 35 78.0 team1-TFIDF_bnn_bnn
data download Q0 2202 36 78.0 team1-TFIDF_bnn_bnn
data download Q0 97 37 78.0 team1-TFIDF_bnn_bnn
data download Q0 505 38 78.0 team1-TFIDF_bnn_bnn
data download Q0 2117 39 78.0 team1-TFIDF_bnn_bnn
data download Q0 702 40 78.0 team1-TFIDF_bnn_bnn
data download Q0 414 41 78.0 team1-TFIDF_bnn_bnn
data download Q0 191 42 78.0 team1-TFIDF_bnn_bnn
data download Q0 2361 43 78.0 team1-TFIDF_bnn_bnn
data download Q0 2024 44 78.0 team1-TFIDF_bnn_bnn
data download Q0 2113 45 78.0 team1-TFIDF_bnn_bnn
data download Q0 1014 46 78.0 team1-TFIDF_bnn_bnn
data download Q0 1001 47 78.0 team1-TFIDF_bnn_bnn
data download Q0 951 48 78.0 team1-TFIDF_bnn_bnn
data download Q0 112 49 78.0 team1-TFIDF_bnn_bnn
samtools Q0 449 0 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2145 1 44.0 team1-TFIDF_bnn_bnn
samtools Q0 285 2 44.0 team1-TFIDF_bnn_bnn
samtools Q0 453 3 44.0 team1-TFIDF_bnn_bnn
samtools Q0 1002 4 44.0 team1-TFIDF_bnn_bnn
samtools Q0 396 5 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2204 6 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2149 7 44.0 team1-TFIDF_bnn_bnn
samtools Q0 908 8 44.0 team1-TFIDF_bnn_bnn
samtools Q0 1010 9 44.0 team1-TFIDF_bnn_bnn
samtools Q0 401 10 44.0 team1-TFIDF_bnn_bnn
samtools Q0 525 11 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2302 12 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2242 13 44.0 team1-TFIDF_bnn_bnn
samtools Q0 134 14 44.0 team1-TFIDF_bnn_bnn
samtools Q0 2119 15 44.0 team1-TFIDF_bnn_bnn
samtools Q0 157 16 12.0 team1-TFIDF_bnn_bnn
samtools Q0 2363 17 12.0 team1-TFIDF_bnn_bnn
samtools Q0 403 18 12.0 team1-TFIDF_bnn_bnn
samtools Q0 253 19 12.0 team1-TFIDF_bnn_bnn
samtools Q0 237 20 12.0 team1-TFIDF_bnn_bnn
samtools Q0 531 21 12.0 team1-TFIDF_bnn_bnn
mapq Q0 661 0 6.0 team1-TFIDF_bnn_bnn
mapq Q0 508 1 6.0 team1-TFIDF_bnn_bnn
mapq Q0 2081 2 2.0 team1-TFIDF_bnn_bnn
genotyping Q0 150 0 10.0 team1-TFIDF_bnn_bnn
genotyping Q0 329 1 10.0 team1-TFIDF_bnn_bnn
genotyping Q0 336 2 6.0 team1-TFIDF_bnn_bnn
genotyping Q0 73 3 6.0 team1-TFIDF_bnn_bnn
genotyping Q0 761 4 6.0 team1-TFIDF_bnn_bnn
refseq Q0 818 0 20.0 team1-TFIDF_bnn_bnn
refseq Q0 798 1 20.0 team1-TFIDF_bnn_bnn
refseq Q0 650 2 20.0 team1-TFIDF_bnn_bnn
refseq Q0 2186 3 20.0 team1-TFIDF_bnn_bnn
refseq Q0 2237 4 20.0 team1-TFIDF_bnn_bnn
refseq Q0 328 5 20.0 team1-TFIDF_bnn_bnn
refseq Q0 646 6 20.0 team1-TFIDF_bnn_bnn
refseq Q0 2083 7 20.0 team1-TFIDF_bnn_bnn
refseq Q0 741 8 6.0 team1-TFIDF_bnn_bnn
refseq Q0 2130 9 6.0 team1-TFIDF_bnn_bnn
refseq Q0 21 10 6.0 team1-TFIDF_bnn_bnn
bwa Q0 36 0 30.0 team1-TFIDF_bnn_bnn
bwa Q0 2149 1 30.0 team1-TFIDF_bnn_bnn
bwa Q0 407 2 30.0 team1-TFIDF_bnn_bnn
bwa Q0 500 3 30.0 team1-TFIDF_bnn_bnn
bwa Q0 945 4 30.0 team1-TFIDF_bnn_bnn
bwa Q0 1010 5 30.0 team1-TFIDF_bnn_bnn
bwa Q0 308 6 30.0 team1-TFIDF_bnn_bnn
bwa Q0 908 7 30.0 team1-TFIDF_bnn_bnn
bwa Q0 404 8 30.0 team1-TFIDF_bnn_bnn
bwa Q0 237 9 30.0 team1-TFIDF_bnn_bnn
bwa Q0 418 10 10.0 team1-TFIDF_bnn_bnn
bwa Q0 289 11 10.0 team1-TFIDF_bnn_bnn
bwa Q0 508 12 10.0 team1-TFIDF_bnn_bnn
bwa Q0 15 13 10.0 team1-TFIDF_bnn_bnn
bwa Q0 396 14 10.0 team1-TFIDF_bnn_bnn
modelling Q0 2339 0 4.0 team1-TFIDF_bnn_bnn
modelling Q0 191 1 4.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 388 0 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 5 1 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 289 2 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 802 3 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 378 4 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 692 5 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 107 6 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 620 7 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 950 8 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 242 9 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 882 10 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 294 11 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 570 12 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 375 13 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 62 14 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 125 15 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 103 16 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 765 17 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 741 18 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 935 19 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 225 20 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 703 21 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 91 22 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 705 23 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 452 24 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 837 25 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 595 26 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 159 27 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 45 28 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 303 29 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 847 30 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 815 31 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 722 32 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 561 33 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 817 34 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 343 35 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 732 36 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 818 37 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 228 38 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 51 39 146.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 979 40 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 2164 41 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 2043 42 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 19 43 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 2156 44 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 110 45 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 2179 46 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 548 47 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 724 48 46.0 team1-TFIDF_bnn_bnn
sequence annotation Q0 1 49 46.0 team1-TFIDF_bnn_bnn
data request Q0 9 0 266.0 team1-TFIDF_bnn_bnn
data request Q0 19 1 266.0 team1-TFIDF_bnn_bnn
data request Q0 418 2 266.0 team1-TFIDF_bnn_bnn
data request Q0 66 3 266.0 team1-TFIDF_bnn_bnn
data request Q0 242 4 266.0 team1-TFIDF_bnn_bnn
data request Q0 626 5 266.0 team1-TFIDF_bnn_bnn
data request Q0 627 6 266.0 team1-TFIDF_bnn_bnn
data request Q0 372 7 266.0 team1-TFIDF_bnn_bnn
data request Q0 294 8 266.0 team1-TFIDF_bnn_bnn
data request Q0 195 9 266.0 team1-TFIDF_bnn_bnn
data request Q0 196 10 266.0 team1-TFIDF_bnn_bnn
data request Q0 452 11 266.0 team1-TFIDF_bnn_bnn
data request Q0 282 12 266.0 team1-TFIDF_bnn_bnn
data request Q0 328 13 266.0 team1-TFIDF_bnn_bnn
data request Q0 584 14 266.0 team1-TFIDF_bnn_bnn
data request Q0 73 15 266.0 team1-TFIDF_bnn_bnn
data request Q0 232 16 266.0 team1-TFIDF_bnn_bnn
data request Q0 83 17 266.0 team1-TFIDF_bnn_bnn
data request Q0 610 18 266.0 team1-TFIDF_bnn_bnn
data request Q0 395 19 266.0 team1-TFIDF_bnn_bnn
data request Q0 283 20 266.0 team1-TFIDF_bnn_bnn
data request Q0 308 21 266.0 team1-TFIDF_bnn_bnn
data request Q0 343 22 266.0 team1-TFIDF_bnn_bnn
data request Q0 565 23 266.0 team1-TFIDF_bnn_bnn
data request Q0 89 24 266.0 team1-TFIDF_bnn_bnn
data request Q0 92 25 266.0 team1-TFIDF_bnn_bnn
data request Q0 567 26 266.0 team1-TFIDF_bnn_bnn
data request Q0 351 27 266.0 team1-TFIDF_bnn_bnn
data request Q0 481 28 266.0 team1-TFIDF_bnn_bnn
data request Q0 29 29 266.0 team1-TFIDF_bnn_bnn
data request Q0 57 30 266.0 team1-TFIDF_bnn_bnn
data request Q0 609 31 266.0 team1-TFIDF_bnn_bnn
data request Q0 103 32 266.0 team1-TFIDF_bnn_bnn
data request Q0 488 33 266.0 team1-TFIDF_bnn_bnn
data request Q0 456 34 78.0 team1-TFIDF_bnn_bnn
data request Q0 299 35 78.0 team1-TFIDF_bnn_bnn
data request Q0 2117 36 78.0 team1-TFIDF_bnn_bnn
data request Q0 411 37 78.0 team1-TFIDF_bnn_bnn
data request Q0 771 38 78.0 team1-TFIDF_bnn_bnn
data request Q0 278 39 78.0 team1-TFIDF_bnn_bnn
data request Q0 962 40 78.0 team1-TFIDF_bnn_bnn
data request Q0 120 41 78.0 team1-TFIDF_bnn_bnn
data request Q0 253 42 78.0 team1-TFIDF_bnn_bnn
data request Q0 2289 43 78.0 team1-TFIDF_bnn_bnn
data request Q0 702 44 78.0 team1-TFIDF_bnn_bnn
data request Q0 2065 45 78.0 team1-TFIDF_bnn_bnn
data request Q0 462 46 78.0 team1-TFIDF_bnn_bnn
data request Q0 2098 47 78.0 team1-TFIDF_bnn_bnn
data request Q0 2183 48 78.0 team1-TFIDF_bnn_bnn
data request Q0 97 49 78.0 team1-TFIDF_bnn_bnn
rna splicing Q0 774 0 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2056 1 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2298 2 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2194 3 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2165 4 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 884 5 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 372 6 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 540 7 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 924 8 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 703 9 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2242 10 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2215 11 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2119 12 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2140 13 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 584 14 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2088 15 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 969 16 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 333 17 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 395 18 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2068 19 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 46 20 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 278 21 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 232 22 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 238 23 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 57 24 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 524 25 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2101 26 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2199 27 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2356 28 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 1018 29 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 561 30 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 751 31 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 51 32 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 280 33 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 909 34 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 664 35 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 568 36 104.0 team1-TFIDF_bnn_bnn
rna splicing Q0 771 37 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 518 38 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 528 39 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 441 40 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 610 41 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2329 42 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 693 43 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 1019 44 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 299 45 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 687 46 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 2282 47 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 942 48 34.0 team1-TFIDF_bnn_bnn
rna splicing Q0 52 49 34.0 team1-TFIDF_bnn_bnn
structural variation Q0 2275 0 14.0 team1-TFIDF_bnn_bnn
structural variation Q0 796 1 14.0 team1-TFIDF_bnn_bnn
structural variation Q0 2223 2 14.0 team1-TFIDF_bnn_bnn
structural variation Q0 92 3 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 438 4 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 73 5 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 329 6 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 52 7 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 120 8 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 2067 9 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 271 10 10.0 team1-TFIDF_bnn_bnn
structural variation Q0 264 11 10.0 team1-TFIDF_bnn_bnn
shell Q0 357 0 4.0 team1-TFIDF_bnn_bnn
shell Q0 716 1 4.0 team1-TFIDF_bnn_bnn
centrifuge Q0 306 0 2.0 team1-TFIDF_bnn_bnn
de bruijn Q0 2145 0 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 2204 1 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 584 2 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 343 3 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 2378 4 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 150 5 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 2308 6 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 942 7 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 46 8 24.0 team1-TFIDF_bnn_bnn
de bruijn Q0 156 9 6.0 team1-TFIDF_bnn_bnn
de bruijn Q0 611 10 6.0 team1-TFIDF_bnn_bnn
de bruijn Q0 561 11 4.0 team1-TFIDF_bnn_bnn
de bruijn Q0 146 12 2.0 team1-TFIDF_bnn_bnn
sambamba Q0 531 0 2.0 team1-TFIDF_bnn_bnn
sambamba Q0 403 1 2.0 team1-TFIDF_bnn_bnn
gsea Q0 149 0 4.0 team1-TFIDF_bnn_bnn
gsea Q0 2073 1 4.0 team1-TFIDF_bnn_bnn
biopython Q0 388 0 24.0 team1-TFIDF_bnn_bnn
biopython Q0 837 1 24.0 team1-TFIDF_bnn_bnn
biopython Q0 692 2 24.0 team1-TFIDF_bnn_bnn
biopython Q0 45 3 24.0 team1-TFIDF_bnn_bnn
biopython Q0 2230 4 24.0 team1-TFIDF_bnn_bnn
biopython Q0 709 5 24.0 team1-TFIDF_bnn_bnn
biopython Q0 882 6 24.0 team1-TFIDF_bnn_bnn
biopython Q0 676 7 12.0 team1-TFIDF_bnn_bnn
biopython Q0 943 8 12.0 team1-TFIDF_bnn_bnn
biopython Q0 2200 9 12.0 team1-TFIDF_bnn_bnn
biopython Q0 892 10 12.0 team1-TFIDF_bnn_bnn
biopython Q0 307 11 12.0 team1-TFIDF_bnn_bnn
biopython Q0 2043 12 12.0 team1-TFIDF_bnn_bnn
alignment Q0 705 0 80.0 team1-TFIDF_bnn_bnn
alignment Q0 191 1 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2049 2 80.0 team1-TFIDF_bnn_bnn
alignment Q0 1018 3 80.0 team1-TFIDF_bnn_bnn
alignment Q0 570 4 80.0 team1-TFIDF_bnn_bnn
alignment Q0 1014 5 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2036 6 80.0 team1-TFIDF_bnn_bnn
alignment Q0 500 7 80.0 team1-TFIDF_bnn_bnn
alignment Q0 646 8 80.0 team1-TFIDF_bnn_bnn
alignment Q0 650 9 80.0 team1-TFIDF_bnn_bnn
alignment Q0 1010 10 80.0 team1-TFIDF_bnn_bnn
alignment Q0 626 11 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2034 12 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2349 13 80.0 team1-TFIDF_bnn_bnn
alignment Q0 1001 14 80.0 team1-TFIDF_bnn_bnn
alignment Q0 103 15 80.0 team1-TFIDF_bnn_bnn
alignment Q0 796 16 80.0 team1-TFIDF_bnn_bnn
alignment Q0 357 17 80.0 team1-TFIDF_bnn_bnn
alignment Q0 228 18 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2186 19 80.0 team1-TFIDF_bnn_bnn
alignment Q0 994 20 80.0 team1-TFIDF_bnn_bnn
alignment Q0 98 21 80.0 team1-TFIDF_bnn_bnn
alignment Q0 289 22 80.0 team1-TFIDF_bnn_bnn
alignment Q0 414 23 80.0 team1-TFIDF_bnn_bnn
alignment Q0 736 24 80.0 team1-TFIDF_bnn_bnn
alignment Q0 135 25 80.0 team1-TFIDF_bnn_bnn
alignment Q0 396 26 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2202 27 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2068 28 80.0 team1-TFIDF_bnn_bnn
alignment Q0 847 29 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2316 30 80.0 team1-TFIDF_bnn_bnn
alignment Q0 972 31 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2242 32 80.0 team1-TFIDF_bnn_bnn
alignment Q0 2119 33 80.0 team1-TFIDF_bnn_bnn
alignment Q0 969 34 80.0 team1-TFIDF_bnn_bnn
alignment Q0 36 35 12.0 team1-TFIDF_bnn_bnn
alignment Q0 110 36 12.0 team1-TFIDF_bnn_bnn
alignment Q0 51 37 12.0 team1-TFIDF_bnn_bnn
alignment Q0 997 38 12.0 team1-TFIDF_bnn_bnn
alignment Q0 2203 39 12.0 team1-TFIDF_bnn_bnn
alignment Q0 508 40 12.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 135 0 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 524 1 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 149 2 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 939 3 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 761 4 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 842 5 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 945 6 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2131 7 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2097 8 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 1012 9 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 372 10 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2163 11 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 627 12 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 731 13 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 92 14 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2098 15 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2140 16 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 609 17 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2199 18 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 52 19 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 997 20 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2149 21 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 230 22 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 949 23 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2028 24 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 654 25 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2073 26 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 954 27 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 242 28 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 540 29 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 62 30 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 318 31 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 584 32 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 125 33 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 194 34 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 143 35 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 702 36 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 1014 37 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 583 38 122.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 314 39 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 774 40 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 664 41 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 103 42 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2282 43 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 112 44 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 886 45 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2298 46 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 254 47 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2346 48 46.0 team1-TFIDF_bnn_bnn
bootstrap analysis Q0 2321 49 46.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 388 0 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 5 1 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 561 2 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 817 3 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 225 4 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 818 5 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 741 6 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 692 7 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 107 8 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 620 9 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 950 10 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 242 11 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 882 12 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 159 13 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 62 14 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 703 15 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 375 16 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 378 17 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 802 18 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 125 19 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 452 20 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 765 21 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 837 22 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 294 23 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 935 24 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 70 25 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 45 26 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 722 27 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 595 28 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 303 29 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 343 30 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 91 31 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 815 32 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 732 33 146.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 103 34 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 796 35 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 98 36 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 994 37 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 228 38 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 2242 39 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 650 40 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 500 41 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 289 42 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 2186 43 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 2036 44 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 705 45 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 1014 46 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 570 47 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 2316 48 80.0 team1-TFIDF_bnn_bnn
sequence alignment Q0 1018 49 80.0 team1-TFIDF_bnn_bnn
array cgh Q0 745 0 4.0 team1-TFIDF_bnn_bnn
array cgh Q0 45 1 4.0 team1-TFIDF_bnn_bnn
data mining Q0 9 0 266.0 team1-TFIDF_bnn_bnn
data mining Q0 19 1 266.0 team1-TFIDF_bnn_bnn
data mining Q0 418 2 266.0 team1-TFIDF_bnn_bnn
data mining Q0 66 3 266.0 team1-TFIDF_bnn_bnn
data mining Q0 242 4 266.0 team1-TFIDF_bnn_bnn
data mining Q0 626 5 266.0 team1-TFIDF_bnn_bnn
data mining Q0 627 6 266.0 team1-TFIDF_bnn_bnn
data mining Q0 195 7 266.0 team1-TFIDF_bnn_bnn
data mining Q0 372 8 266.0 team1-TFIDF_bnn_bnn
data mining Q0 294 9 266.0 team1-TFIDF_bnn_bnn
data mining Q0 196 10 266.0 team1-TFIDF_bnn_bnn
data mining Q0 452 11 266.0 team1-TFIDF_bnn_bnn
data mining Q0 328 12 266.0 team1-TFIDF_bnn_bnn
data mining Q0 282 13 266.0 team1-TFIDF_bnn_bnn
data mining Q0 584 14 266.0 team1-TFIDF_bnn_bnn
data mining Q0 488 15 266.0 team1-TFIDF_bnn_bnn
data mining Q0 73 16 266.0 team1-TFIDF_bnn_bnn
data mining Q0 103 17 266.0 team1-TFIDF_bnn_bnn
data mining Q0 308 18 266.0 team1-TFIDF_bnn_bnn
data mining Q0 609 19 266.0 team1-TFIDF_bnn_bnn
data mining Q0 83 20 266.0 team1-TFIDF_bnn_bnn
data mining Q0 395 21 266.0 team1-TFIDF_bnn_bnn
data mining Q0 283 22 266.0 team1-TFIDF_bnn_bnn
data mining Q0 565 23 266.0 team1-TFIDF_bnn_bnn
data mining Q0 343 24 266.0 team1-TFIDF_bnn_bnn
data mining Q0 89 25 266.0 team1-TFIDF_bnn_bnn
data mining Q0 92 26 266.0 team1-TFIDF_bnn_bnn
data mining Q0 567 27 266.0 team1-TFIDF_bnn_bnn
data mining Q0 351 28 266.0 team1-TFIDF_bnn_bnn
data mining Q0 481 29 266.0 team1-TFIDF_bnn_bnn
data mining Q0 29 30 266.0 team1-TFIDF_bnn_bnn
data mining Q0 57 31 266.0 team1-TFIDF_bnn_bnn
data mining Q0 610 32 266.0 team1-TFIDF_bnn_bnn
data mining Q0 232 33 266.0 team1-TFIDF_bnn_bnn
data mining Q0 456 34 78.0 team1-TFIDF_bnn_bnn
data mining Q0 299 35 78.0 team1-TFIDF_bnn_bnn
data mining Q0 2117 36 78.0 team1-TFIDF_bnn_bnn
data mining Q0 253 37 78.0 team1-TFIDF_bnn_bnn
data mining Q0 278 38 78.0 team1-TFIDF_bnn_bnn
data mining Q0 899 39 78.0 team1-TFIDF_bnn_bnn
data mining Q0 1014 40 78.0 team1-TFIDF_bnn_bnn
data mining Q0 505 41 78.0 team1-TFIDF_bnn_bnn
data mining Q0 771 42 78.0 team1-TFIDF_bnn_bnn
data mining Q0 191 43 78.0 team1-TFIDF_bnn_bnn
data mining Q0 702 44 78.0 team1-TFIDF_bnn_bnn
data mining Q0 458 45 78.0 team1-TFIDF_bnn_bnn
data mining Q0 462 46 78.0 team1-TFIDF_bnn_bnn
data mining Q0 2202 47 78.0 team1-TFIDF_bnn_bnn
data mining Q0 97 48 78.0 team1-TFIDF_bnn_bnn
data mining Q0 350 49 78.0 team1-TFIDF_bnn_bnn
rna seq Q0 2051 0 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 774 1 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2300 2 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2043 3 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 524 4 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2199 5 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2298 6 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 280 7 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2101 8 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 695 9 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 372 10 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 751 11 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 238 12 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 664 13 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 909 14 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 540 15 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 232 16 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 703 17 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 960 18 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2242 19 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2119 20 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2215 21 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 584 22 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 969 23 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2179 24 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2194 25 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2088 26 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 83 27 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2068 28 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 228 29 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 661 30 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 561 31 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2028 32 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 278 33 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 51 34 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 2165 35 106.0 team1-TFIDF_bnn_bnn
rna seq Q0 1018 36 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 2356 37 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 884 38 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 568 39 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 2056 40 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 924 41 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 2140 42 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 333 43 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 46 44 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 57 45 104.0 team1-TFIDF_bnn_bnn
rna seq Q0 2378 46 36.0 team1-TFIDF_bnn_bnn
rna seq Q0 1014 47 36.0 team1-TFIDF_bnn_bnn
rna seq Q0 414 48 36.0 team1-TFIDF_bnn_bnn
rna seq Q0 2183 49 36.0 team1-TFIDF_bnn_bnn
rna alignment Q0 774 0 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 395 1 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2194 2 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2298 3 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2088 4 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 46 5 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 232 6 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 278 7 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 238 8 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 751 9 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2199 10 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 561 11 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 372 12 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 524 13 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 280 14 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2356 15 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 884 16 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2165 17 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 664 18 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2101 19 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 568 20 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 57 21 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2056 22 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 540 23 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 703 24 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 924 25 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 584 26 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 909 27 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 333 28 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2215 29 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2140 30 104.0 team1-TFIDF_bnn_bnn
rna alignment Q0 1018 31 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 650 32 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 994 33 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 972 34 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 969 35 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 228 36 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 357 37 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2242 38 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 103 39 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2349 40 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2068 41 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 570 42 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2034 43 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2036 44 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 2186 45 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 626 46 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 1010 47 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 500 48 80.0 team1-TFIDF_bnn_bnn
rna alignment Q0 1014 49 80.0 team1-TFIDF_bnn_bnn
gaf Q0 568 0 2.0 team1-TFIDF_bnn_bnn
grch38 Q0 2081 0 12.0 team1-TFIDF_bnn_bnn
grch38 Q0 326 1 12.0 team1-TFIDF_bnn_bnn
grch38 Q0 531 2 12.0 team1-TFIDF_bnn_bnn
grch38 Q0 2293 3 6.0 team1-TFIDF_bnn_bnn
grch38 Q0 752 4 6.0 team1-TFIDF_bnn_bnn
grch38 Q0 604 5 6.0 team1-TFIDF_bnn_bnn
iclip Q0 83 0 2.0 team1-TFIDF_bnn_bnn
coreutils Q0 974 0 2.0 team1-TFIDF_bnn_bnn
linux Q0 935 0 4.0 team1-TFIDF_bnn_bnn
linux Q0 2078 1 4.0 team1-TFIDF_bnn_bnn
esp6500 Q0 2289 0 2.0 team1-TFIDF_bnn_bnn
genomics Q0 752 0 10.0 team1-TFIDF_bnn_bnn
genomics Q0 283 1 10.0 team1-TFIDF_bnn_bnn
genomics Q0 195 2 10.0 team1-TFIDF_bnn_bnn
genomics Q0 357 3 10.0 team1-TFIDF_bnn_bnn
genomics Q0 458 4 10.0 team1-TFIDF_bnn_bnn
genomics Q0 308 5 4.0 team1-TFIDF_bnn_bnn
genomics Q0 771 6 4.0 team1-TFIDF_bnn_bnn
phylogenetics Q0 626 0 4.0 team1-TFIDF_bnn_bnn
phylogenetics Q0 103 1 4.0 team1-TFIDF_bnn_bnn
mpileup Q0 449 0 6.0 team1-TFIDF_bnn_bnn
mpileup Q0 253 1 4.0 team1-TFIDF_bnn_bnn
mpileup Q0 237 2 4.0 team1-TFIDF_bnn_bnn
perl Q0 2149 0 8.0 team1-TFIDF_bnn_bnn
perl Q0 110 1 8.0 team1-TFIDF_bnn_bnn
perl Q0 264 2 8.0 team1-TFIDF_bnn_bnn
perl Q0 2341 3 8.0 team1-TFIDF_bnn_bnn
gistic Q0 251 0 2.0 team1-TFIDF_bnn_bnn
human Q0 1 0 72.0 team1-TFIDF_bnn_bnn
human Q0 513 1 72.0 team1-TFIDF_bnn_bnn
human Q0 2241 2 72.0 team1-TFIDF_bnn_bnn
human Q0 2234 3 72.0 team1-TFIDF_bnn_bnn
human Q0 518 4 72.0 team1-TFIDF_bnn_bnn
human Q0 27 5 72.0 team1-TFIDF_bnn_bnn
human Q0 438 6 72.0 team1-TFIDF_bnn_bnn
human Q0 565 7 72.0 team1-TFIDF_bnn_bnn
human Q0 2098 8 72.0 team1-TFIDF_bnn_bnn
human Q0 945 9 72.0 team1-TFIDF_bnn_bnn
human Q0 558 10 72.0 team1-TFIDF_bnn_bnn
human Q0 951 11 72.0 team1-TFIDF_bnn_bnn
human Q0 288 12 72.0 team1-TFIDF_bnn_bnn
human Q0 584 13 72.0 team1-TFIDF_bnn_bnn
human Q0 191 14 72.0 team1-TFIDF_bnn_bnn
human Q0 228 15 72.0 team1-TFIDF_bnn_bnn
human Q0 587 16 72.0 team1-TFIDF_bnn_bnn
human Q0 678 17 72.0 team1-TFIDF_bnn_bnn
human Q0 901 18 72.0 team1-TFIDF_bnn_bnn
human Q0 531 19 72.0 team1-TFIDF_bnn_bnn
human Q0 2029 20 72.0 team1-TFIDF_bnn_bnn
human Q0 110 21 72.0 team1-TFIDF_bnn_bnn
human Q0 664 22 72.0 team1-TFIDF_bnn_bnn
human Q0 326 23 72.0 team1-TFIDF_bnn_bnn
human Q0 278 24 72.0 team1-TFIDF_bnn_bnn
human Q0 785 25 22.0 team1-TFIDF_bnn_bnn
human Q0 654 26 22.0 team1-TFIDF_bnn_bnn
human Q0 168 27 22.0 team1-TFIDF_bnn_bnn
human Q0 553 28 22.0 team1-TFIDF_bnn_bnn
human Q0 821 29 22.0 team1-TFIDF_bnn_bnn
human Q0 829 30 22.0 team1-TFIDF_bnn_bnn
human Q0 2081 31 22.0 team1-TFIDF_bnn_bnn
human Q0 998 32 22.0 team1-TFIDF_bnn_bnn
human Q0 2216 33 22.0 team1-TFIDF_bnn_bnn
human Q0 2049 34 22.0 team1-TFIDF_bnn_bnn
human Q0 5 35 22.0 team1-TFIDF_bnn_bnn
conversion Q0 2242 0 16.0 team1-TFIDF_bnn_bnn
conversion Q0 694 1 16.0 team1-TFIDF_bnn_bnn
conversion Q0 939 2 16.0 team1-TFIDF_bnn_bnn
conversion Q0 91 3 16.0 team1-TFIDF_bnn_bnn
conversion Q0 522 4 16.0 team1-TFIDF_bnn_bnn
conversion Q0 525 5 16.0 team1-TFIDF_bnn_bnn
conversion Q0 2068 6 16.0 team1-TFIDF_bnn_bnn
conversion Q0 228 7 2.0 team1-TFIDF_bnn_bnn
coverage Q0 321 0 50.0 team1-TFIDF_bnn_bnn
coverage Q0 191 1 50.0 team1-TFIDF_bnn_bnn
coverage Q0 449 2 50.0 team1-TFIDF_bnn_bnn
coverage Q0 1019 3 50.0 team1-TFIDF_bnn_bnn
coverage Q0 438 4 50.0 team1-TFIDF_bnn_bnn
coverage Q0 402 5 50.0 team1-TFIDF_bnn_bnn
coverage Q0 2275 6 50.0 team1-TFIDF_bnn_bnn
coverage Q0 945 7 50.0 team1-TFIDF_bnn_bnn
coverage Q0 722 8 50.0 team1-TFIDF_bnn_bnn
coverage Q0 242 9 50.0 team1-TFIDF_bnn_bnn
coverage Q0 531 10 50.0 team1-TFIDF_bnn_bnn
coverage Q0 2145 11 50.0 team1-TFIDF_bnn_bnn
coverage Q0 672 12 50.0 team1-TFIDF_bnn_bnn
coverage Q0 608 13 50.0 team1-TFIDF_bnn_bnn
coverage Q0 253 14 50.0 team1-TFIDF_bnn_bnn
coverage Q0 73 15 50.0 team1-TFIDF_bnn_bnn
coverage Q0 525 16 50.0 team1-TFIDF_bnn_bnn
coverage Q0 2318 17 50.0 team1-TFIDF_bnn_bnn
coverage Q0 2204 18 14.0 team1-TFIDF_bnn_bnn
coverage Q0 329 19 14.0 team1-TFIDF_bnn_bnn
coverage Q0 2216 20 14.0 team1-TFIDF_bnn_bnn
coverage Q0 2152 21 14.0 team1-TFIDF_bnn_bnn
coverage Q0 524 22 14.0 team1-TFIDF_bnn_bnn
coverage Q0 2101 23 14.0 team1-TFIDF_bnn_bnn
coverage Q0 81 24 14.0 team1-TFIDF_bnn_bnn
gatk Q0 321 0 16.0 team1-TFIDF_bnn_bnn
gatk Q0 191 1 16.0 team1-TFIDF_bnn_bnn
gatk Q0 462 2 16.0 team1-TFIDF_bnn_bnn
gatk Q0 285 3 16.0 team1-TFIDF_bnn_bnn
gatk Q0 157 4 16.0 team1-TFIDF_bnn_bnn
gatk Q0 426 5 16.0 team1-TFIDF_bnn_bnn
gatk Q0 73 6 16.0 team1-TFIDF_bnn_bnn
gatk Q0 407 7 16.0 team1-TFIDF_bnn_bnn
seurat Q0 779 0 4.0 team1-TFIDF_bnn_bnn
seurat Q0 2356 1 2.0 team1-TFIDF_bnn_bnn
medip seq Q0 2051 0 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2179 1 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2300 2 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 774 3 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 909 4 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2119 5 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2165 6 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 584 7 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 751 8 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 238 9 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 540 10 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 969 11 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2194 12 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2215 13 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 83 14 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2068 15 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2088 16 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 228 17 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 232 18 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 661 19 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2028 20 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 561 21 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 524 22 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 278 23 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2242 24 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 960 25 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 703 26 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 51 27 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2101 28 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2043 29 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 372 30 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2298 31 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 2199 32 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 280 33 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 695 34 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 664 35 106.0 team1-TFIDF_bnn_bnn
medip seq Q0 687 36 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 414 37 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 1014 38 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 693 39 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 620 40 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 722 41 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 2329 42 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 771 43 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 2378 44 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 92 45 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 2282 46 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 395 47 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 610 48 36.0 team1-TFIDF_bnn_bnn
medip seq Q0 253 49 36.0 team1-TFIDF_bnn_bnn
hts Q0 422 0 2.0 team1-TFIDF_bnn_bnn
go Q0 769 0 24.0 team1-TFIDF_bnn_bnn
go Q0 254 1 24.0 team1-TFIDF_bnn_bnn
go Q0 2333 2 24.0 team1-TFIDF_bnn_bnn
go Q0 2059 3 24.0 team1-TFIDF_bnn_bnn
go Q0 817 4 24.0 team1-TFIDF_bnn_bnn
go Q0 2323 5 24.0 team1-TFIDF_bnn_bnn
go Q0 584 6 24.0 team1-TFIDF_bnn_bnn
go Q0 2343 7 24.0 team1-TFIDF_bnn_bnn
go Q0 1012 8 24.0 team1-TFIDF_bnn_bnn
go Q0 962 9 24.0 team1-TFIDF_bnn_bnn
go Q0 2346 10 4.0 team1-TFIDF_bnn_bnn
go Q0 568 11 4.0 team1-TFIDF_bnn_bnn
simulated data Q0 9 0 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 19 1 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 418 2 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 66 3 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 242 4 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 626 5 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 627 6 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 195 7 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 372 8 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 294 9 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 196 10 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 452 11 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 328 12 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 282 13 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 584 14 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 488 15 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 73 16 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 103 17 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 308 18 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 609 19 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 83 20 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 395 21 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 283 22 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 565 23 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 343 24 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 89 25 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 92 26 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 567 27 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 351 28 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 481 29 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 29 30 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 57 31 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 610 32 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 232 33 266.0 team1-TFIDF_bnn_bnn
simulated data Q0 456 34 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 299 35 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 2117 36 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 253 37 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 278 38 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 899 39 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 1014 40 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 505 41 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 771 42 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 191 43 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 702 44 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 458 45 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 462 46 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 2202 47 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 97 48 78.0 team1-TFIDF_bnn_bnn
simulated data Q0 350 49 78.0 team1-TFIDF_bnn_bnn
file formats Q0 516 0 234.0 team1-TFIDF_bnn_bnn
file formats Q0 266 1 234.0 team1-TFIDF_bnn_bnn
file formats Q0 531 2 234.0 team1-TFIDF_bnn_bnn
file formats Q0 561 3 234.0 team1-TFIDF_bnn_bnn
file formats Q0 110 4 234.0 team1-TFIDF_bnn_bnn
file formats Q0 628 5 234.0 team1-TFIDF_bnn_bnn
file formats Q0 375 6 234.0 team1-TFIDF_bnn_bnn
file formats Q0 253 7 234.0 team1-TFIDF_bnn_bnn
file formats Q0 280 8 234.0 team1-TFIDF_bnn_bnn
file formats Q0 694 9 234.0 team1-TFIDF_bnn_bnn
file formats Q0 525 10 234.0 team1-TFIDF_bnn_bnn
file formats Q0 153 11 234.0 team1-TFIDF_bnn_bnn
file formats Q0 702 12 234.0 team1-TFIDF_bnn_bnn
file formats Q0 282 13 234.0 team1-TFIDF_bnn_bnn
file formats Q0 322 14 234.0 team1-TFIDF_bnn_bnn
file formats Q0 157 15 234.0 team1-TFIDF_bnn_bnn
file formats Q0 288 16 234.0 team1-TFIDF_bnn_bnn
file formats Q0 289 17 234.0 team1-TFIDF_bnn_bnn
file formats Q0 336 18 234.0 team1-TFIDF_bnn_bnn
file formats Q0 81 19 234.0 team1-TFIDF_bnn_bnn
file formats Q0 91 20 234.0 team1-TFIDF_bnn_bnn
file formats Q0 351 21 234.0 team1-TFIDF_bnn_bnn
file formats Q0 608 22 234.0 team1-TFIDF_bnn_bnn
file formats Q0 745 23 234.0 team1-TFIDF_bnn_bnn
file formats Q0 237 24 234.0 team1-TFIDF_bnn_bnn
file formats Q0 716 25 88.0 team1-TFIDF_bnn_bnn
file formats Q0 528 26 88.0 team1-TFIDF_bnn_bnn
file formats Q0 837 27 88.0 team1-TFIDF_bnn_bnn
file formats Q0 709 28 88.0 team1-TFIDF_bnn_bnn
file formats Q0 453 29 88.0 team1-TFIDF_bnn_bnn
file formats Q0 769 30 88.0 team1-TFIDF_bnn_bnn
file formats Q0 708 31 88.0 team1-TFIDF_bnn_bnn
file formats Q0 752 32 88.0 team1-TFIDF_bnn_bnn
file formats Q0 134 33 88.0 team1-TFIDF_bnn_bnn
file formats Q0 895 34 88.0 team1-TFIDF_bnn_bnn
file formats Q0 567 35 88.0 team1-TFIDF_bnn_bnn
file formats Q0 402 36 88.0 team1-TFIDF_bnn_bnn
file formats Q0 949 37 88.0 team1-TFIDF_bnn_bnn
file formats Q0 2174 38 88.0 team1-TFIDF_bnn_bnn
file formats Q0 307 39 88.0 team1-TFIDF_bnn_bnn
file formats Q0 892 40 88.0 team1-TFIDF_bnn_bnn
file formats Q0 2163 41 88.0 team1-TFIDF_bnn_bnn
file formats Q0 2186 42 88.0 team1-TFIDF_bnn_bnn
file formats Q0 2137 43 88.0 team1-TFIDF_bnn_bnn
file formats Q0 45 44 88.0 team1-TFIDF_bnn_bnn
file formats Q0 264 45 88.0 team1-TFIDF_bnn_bnn
file formats Q0 807 46 88.0 team1-TFIDF_bnn_bnn
file formats Q0 135 47 88.0 team1-TFIDF_bnn_bnn
file formats Q0 783 48 88.0 team1-TFIDF_bnn_bnn
file formats Q0 935 49 88.0 team1-TFIDF_bnn_bnn
bioconductor Q0 81 0 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 751 1 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 2180 2 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 2302 3 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 153 4 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 2140 5 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 2346 6 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 282 7 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 909 8 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 230 9 22.0 team1-TFIDF_bnn_bnn
bioconductor Q0 639 10 2.0 team1-TFIDF_bnn_bnn
pdb Q0 677 0 24.0 team1-TFIDF_bnn_bnn
pdb Q0 972 1 24.0 team1-TFIDF_bnn_bnn
pdb Q0 350 2 24.0 team1-TFIDF_bnn_bnn
pdb Q0 159 3 24.0 team1-TFIDF_bnn_bnn
pdb Q0 646 4 16.0 team1-TFIDF_bnn_bnn
pdb Q0 860 5 16.0 team1-TFIDF_bnn_bnn
pdb Q0 650 6 16.0 team1-TFIDF_bnn_bnn
pdb Q0 2200 7 16.0 team1-TFIDF_bnn_bnn
pdb Q0 783 8 16.0 team1-TFIDF_bnn_bnn
pdb Q0 884 9 16.0 team1-TFIDF_bnn_bnn
pdb Q0 528 10 16.0 team1-TFIDF_bnn_bnn
pdb Q0 694 11 16.0 team1-TFIDF_bnn_bnn
contamination Q0 2194 0 8.0 team1-TFIDF_bnn_bnn
contamination Q0 2338 1 8.0 team1-TFIDF_bnn_bnn
contamination Q0 761 2 8.0 team1-TFIDF_bnn_bnn
contamination Q0 951 3 8.0 team1-TFIDF_bnn_bnn
contamination Q0 351 4 2.0 team1-TFIDF_bnn_bnn
codon Q0 2259 0 10.0 team1-TFIDF_bnn_bnn
codon Q0 125 1 10.0 team1-TFIDF_bnn_bnn
codon Q0 2300 2 10.0 team1-TFIDF_bnn_bnn
codon Q0 732 3 10.0 team1-TFIDF_bnn_bnn
codon Q0 997 4 2.0 team1-TFIDF_bnn_bnn
motifs Q0 594 0 6.0 team1-TFIDF_bnn_bnn
motifs Q0 333 1 4.0 team1-TFIDF_bnn_bnn
motifs Q0 288 2 4.0 team1-TFIDF_bnn_bnn
crispr cas9 Q0 732 0 6.0 team1-TFIDF_bnn_bnn
crispr cas9 Q0 107 1 4.0 team1-TFIDF_bnn_bnn
crispr cas9 Q0 456 2 2.0 team1-TFIDF_bnn_bnn
gse Q0 149 0 2.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 1 0 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 135 1 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 27 2 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 604 3 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 608 4 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 736 5 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 481 6 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 107 7 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 527 8 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 796 9 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 817 10 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 628 11 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 565 12 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 120 13 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 285 14 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 568 15 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 442 16 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 774 17 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 288 18 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 702 19 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 195 20 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 709 21 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 404 22 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 328 23 166.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 372 24 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 375 25 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2068 26 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 844 27 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 970 28 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 807 29 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 732 30 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 989 31 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 278 32 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2081 33 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 351 34 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 637 35 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2036 36 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 908 37 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 174 38 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 98 39 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 361 40 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 687 41 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2028 42 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 242 43 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2293 44 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 693 45 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 438 46 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 2361 47 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 316 48 82.0 team1-TFIDF_bnn_bnn
genome sequencing Q0 191 49 82.0 team1-TFIDF_bnn_bnn
workflow management Q0 2194 0 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 51 1 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 157 2 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 2088 3 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 396 4 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 923 5 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 909 6 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 524 7 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 2054 8 20.0 team1-TFIDF_bnn_bnn
workflow management Q0 970 9 2.0 team1-TFIDF_bnn_bnn
cancer Q0 777 0 12.0 team1-TFIDF_bnn_bnn
cancer Q0 877 1 12.0 team1-TFIDF_bnn_bnn
cancer Q0 462 2 12.0 team1-TFIDF_bnn_bnn
cancer Q0 587 3 12.0 team1-TFIDF_bnn_bnn
cancer Q0 752 4 4.0 team1-TFIDF_bnn_bnn
cancer Q0 143 5 4.0 team1-TFIDF_bnn_bnn
crispr Q0 732 0 6.0 team1-TFIDF_bnn_bnn
crispr Q0 456 1 4.0 team1-TFIDF_bnn_bnn
crispr Q0 107 2 4.0 team1-TFIDF_bnn_bnn
gaussian Q0 434 0 2.0 team1-TFIDF_bnn_bnn
subset Q0 769 0 24.0 team1-TFIDF_bnn_bnn
subset Q0 350 1 24.0 team1-TFIDF_bnn_bnn
subset Q0 285 2 24.0 team1-TFIDF_bnn_bnn
subset Q0 956 3 24.0 team1-TFIDF_bnn_bnn
subset Q0 2306 4 24.0 team1-TFIDF_bnn_bnn
subset Q0 869 5 24.0 team1-TFIDF_bnn_bnn
subset Q0 687 6 24.0 team1-TFIDF_bnn_bnn
subset Q0 2097 7 24.0 team1-TFIDF_bnn_bnn
subset Q0 103 8 24.0 team1-TFIDF_bnn_bnn
subset Q0 969 9 24.0 team1-TFIDF_bnn_bnn
subset Q0 2101 10 24.0 team1-TFIDF_bnn_bnn
subset Q0 2149 11 8.0 team1-TFIDF_bnn_bnn
subset Q0 627 12 8.0 team1-TFIDF_bnn_bnn
subset Q0 2186 13 8.0 team1-TFIDF_bnn_bnn
subset Q0 453 14 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2049 0 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2363 1 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 378 2 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2113 3 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2359 4 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 899 5 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2356 6 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 500 7 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 202 8 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2224 9 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2223 10 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2034 11 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 303 12 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2067 13 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 294 14 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 997 15 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2378 16 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2145 17 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 288 18 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2293 19 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2068 20 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2056 21 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 779 22 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 21 23 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 92 24 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 195 25 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 623 26 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 553 27 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 528 28 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 969 29 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 783 30 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 81 31 70.0 team1-TFIDF_bnn_bnn
software recommendation Q0 609 32 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 594 33 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 777 34 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 2259 35 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 849 36 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 590 37 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 731 38 8.0 team1-TFIDF_bnn_bnn
software recommendation Q0 1016 39 8.0 team1-TFIDF_bnn_bnn
variants Q0 321 0 34.0 team1-TFIDF_bnn_bnn
variants Q0 285 1 34.0 team1-TFIDF_bnn_bnn
variants Q0 796 2 34.0 team1-TFIDF_bnn_bnn
variants Q0 195 3 34.0 team1-TFIDF_bnn_bnn
variants Q0 168 4 34.0 team1-TFIDF_bnn_bnn
variants Q0 722 5 34.0 team1-TFIDF_bnn_bnn
variants Q0 945 6 34.0 team1-TFIDF_bnn_bnn
variants Q0 908 7 34.0 team1-TFIDF_bnn_bnn
variants Q0 654 8 34.0 team1-TFIDF_bnn_bnn
variants Q0 264 9 34.0 team1-TFIDF_bnn_bnn
variants Q0 271 10 34.0 team1-TFIDF_bnn_bnn
variants Q0 73 11 34.0 team1-TFIDF_bnn_bnn
variants Q0 2224 12 34.0 team1-TFIDF_bnn_bnn
variants Q0 587 13 34.0 team1-TFIDF_bnn_bnn
variants Q0 438 14 10.0 team1-TFIDF_bnn_bnn
variants Q0 2223 15 10.0 team1-TFIDF_bnn_bnn
variants Q0 2275 16 10.0 team1-TFIDF_bnn_bnn
variants Q0 120 17 10.0 team1-TFIDF_bnn_bnn
variants Q0 143 18 10.0 team1-TFIDF_bnn_bnn
taxonomy Q0 998 0 2.0 team1-TFIDF_bnn_bnn
software installation Q0 2049 0 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2363 1 70.0 team1-TFIDF_bnn_bnn
software installation Q0 899 2 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2378 3 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2068 4 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2293 5 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2356 6 70.0 team1-TFIDF_bnn_bnn
software installation Q0 500 7 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2034 8 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2359 9 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2223 10 70.0 team1-TFIDF_bnn_bnn
software installation Q0 623 11 70.0 team1-TFIDF_bnn_bnn
software installation Q0 303 12 70.0 team1-TFIDF_bnn_bnn
software installation Q0 553 13 70.0 team1-TFIDF_bnn_bnn
software installation Q0 294 14 70.0 team1-TFIDF_bnn_bnn
software installation Q0 997 15 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2145 16 70.0 team1-TFIDF_bnn_bnn
software installation Q0 378 17 70.0 team1-TFIDF_bnn_bnn
software installation Q0 779 18 70.0 team1-TFIDF_bnn_bnn
software installation Q0 21 19 70.0 team1-TFIDF_bnn_bnn
software installation Q0 92 20 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2056 21 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2067 22 70.0 team1-TFIDF_bnn_bnn
software installation Q0 2224 23 70.0 team1-TFIDF_bnn_bnn
software installation Q0 81 24 70.0 team1-TFIDF_bnn_bnn
software installation Q0 528 25 70.0 team1-TFIDF_bnn_bnn
software installation Q0 288 26 70.0 team1-TFIDF_bnn_bnn
software installation Q0 783 27 70.0 team1-TFIDF_bnn_bnn
software installation Q0 195 28 70.0 team1-TFIDF_bnn_bnn
software installation Q0 969 29 70.0 team1-TFIDF_bnn_bnn
software installation Q0 202 30 70.0 team1-TFIDF_bnn_bnn
software installation Q0 594 31 8.0 team1-TFIDF_bnn_bnn
software installation Q0 2259 32 8.0 team1-TFIDF_bnn_bnn
software installation Q0 1016 33 8.0 team1-TFIDF_bnn_bnn
software installation Q0 590 34 8.0 team1-TFIDF_bnn_bnn
software installation Q0 2113 35 2.0 team1-TFIDF_bnn_bnn
gwas Q0 2098 0 4.0 team1-TFIDF_bnn_bnn
gwas Q0 317 1 4.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 70 0 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 378 1 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 350 2 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 782 3 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 2140 4 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 125 5 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 89 6 18.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 159 7 6.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 57 8 6.0 team1-TFIDF_bnn_bnn
hidden markov models Q0 877 9 6.0 team1-TFIDF_bnn_bnn
mmcif Q0 694 0 2.0 team1-TFIDF_bnn_bnn
normalization Q0 962 0 16.0 team1-TFIDF_bnn_bnn
normalization Q0 2356 1 16.0 team1-TFIDF_bnn_bnn
normalization Q0 2333 2 16.0 team1-TFIDF_bnn_bnn
normalization Q0 505 3 16.0 team1-TFIDF_bnn_bnn
normalization Q0 869 4 16.0 team1-TFIDF_bnn_bnn
normalization Q0 372 5 16.0 team1-TFIDF_bnn_bnn
normalization Q0 52 6 6.0 team1-TFIDF_bnn_bnn
normalization Q0 92 7 6.0 team1-TFIDF_bnn_bnn
normalization Q0 2165 8 6.0 team1-TFIDF_bnn_bnn
dna Q0 321 0 48.0 team1-TFIDF_bnn_bnn
dna Q0 513 1 48.0 team1-TFIDF_bnn_bnn
dna Q0 150 2 48.0 team1-TFIDF_bnn_bnn
dna Q0 98 3 48.0 team1-TFIDF_bnn_bnn
dna Q0 1014 4 48.0 team1-TFIDF_bnn_bnn
dna Q0 692 5 48.0 team1-TFIDF_bnn_bnn
dna Q0 558 6 48.0 team1-TFIDF_bnn_bnn
dna Q0 36 7 48.0 team1-TFIDF_bnn_bnn
dna Q0 1001 8 48.0 team1-TFIDF_bnn_bnn
dna Q0 2156 9 48.0 team1-TFIDF_bnn_bnn
dna Q0 2390 10 48.0 team1-TFIDF_bnn_bnn
dna Q0 110 11 48.0 team1-TFIDF_bnn_bnn
dna Q0 2081 12 48.0 team1-TFIDF_bnn_bnn
dna Q0 540 13 48.0 team1-TFIDF_bnn_bnn
dna Q0 2361 14 48.0 team1-TFIDF_bnn_bnn
dna Q0 375 15 48.0 team1-TFIDF_bnn_bnn
dna Q0 844 16 48.0 team1-TFIDF_bnn_bnn
dna Q0 351 17 48.0 team1-TFIDF_bnn_bnn
dna Q0 97 18 48.0 team1-TFIDF_bnn_bnn
dna Q0 505 19 14.0 team1-TFIDF_bnn_bnn
dna Q0 5 20 14.0 team1-TFIDF_bnn_bnn
dna Q0 288 21 14.0 team1-TFIDF_bnn_bnn
dna Q0 2259 22 14.0 team1-TFIDF_bnn_bnn
dna Q0 1 23 14.0 team1-TFIDF_bnn_bnn
dna Q0 2056 24 14.0 team1-TFIDF_bnn_bnn
dna Q0 19 25 14.0 team1-TFIDF_bnn_bnn
cigar Q0 661 0 12.0 team1-TFIDF_bnn_bnn
cigar Q0 157 1 12.0 team1-TFIDF_bnn_bnn
cigar Q0 637 2 12.0 team1-TFIDF_bnn_bnn
cigar Q0 404 3 6.0 team1-TFIDF_bnn_bnn
cigar Q0 705 4 6.0 team1-TFIDF_bnn_bnn
cigar Q0 719 5 6.0 team1-TFIDF_bnn_bnn
freebayes Q0 407 0 4.0 team1-TFIDF_bnn_bnn
freebayes Q0 73 1 4.0 team1-TFIDF_bnn_bnn
gtf Q0 2242 0 20.0 team1-TFIDF_bnn_bnn
gtf Q0 2068 1 20.0 team1-TFIDF_bnn_bnn
gtf Q0 565 2 20.0 team1-TFIDF_bnn_bnn
gtf Q0 2036 3 20.0 team1-TFIDF_bnn_bnn
gtf Q0 2101 4 20.0 team1-TFIDF_bnn_bnn
gtf Q0 661 5 20.0 team1-TFIDF_bnn_bnn
gtf Q0 604 6 8.0 team1-TFIDF_bnn_bnn
gtf Q0 849 7 8.0 team1-TFIDF_bnn_bnn
gtf Q0 2137 8 8.0 team1-TFIDF_bnn_bnn
gtf Q0 2106 9 8.0 team1-TFIDF_bnn_bnn
flow cytometry Q0 306 0 10.0 team1-TFIDF_bnn_bnn
flow cytometry Q0 920 1 10.0 team1-TFIDF_bnn_bnn
flow cytometry Q0 956 2 6.0 team1-TFIDF_bnn_bnn
flow cytometry Q0 703 3 6.0 team1-TFIDF_bnn_bnn
flow cytometry Q0 434 4 2.0 team1-TFIDF_bnn_bnn
text Q0 2048 0 24.0 team1-TFIDF_bnn_bnn
text Q0 2128 1 24.0 team1-TFIDF_bnn_bnn
text Q0 923 2 24.0 team1-TFIDF_bnn_bnn
text Q0 2186 3 24.0 team1-TFIDF_bnn_bnn
text Q0 568 4 24.0 team1-TFIDF_bnn_bnn
text Q0 962 5 24.0 team1-TFIDF_bnn_bnn
text Q0 453 6 24.0 team1-TFIDF_bnn_bnn
text Q0 878 7 24.0 team1-TFIDF_bnn_bnn
text Q0 307 8 24.0 team1-TFIDF_bnn_bnn
text Q0 264 9 24.0 team1-TFIDF_bnn_bnn
text Q0 81 10 24.0 team1-TFIDF_bnn_bnn
text Q0 884 11 2.0 team1-TFIDF_bnn_bnn
scrnaseq Q0 29 0 2.0 team1-TFIDF_bnn_bnn
ebseq Q0 610 0 4.0 team1-TFIDF_bnn_bnn
ebseq Q0 372 1 2.0 team1-TFIDF_bnn_bnn
staden Q0 692 0 2.0 team1-TFIDF_bnn_bnn
3d structure Q0 2177 0 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 375 1 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 837 2 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 2246 3 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 914 4 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 909 5 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 110 6 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 452 7 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 869 8 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 242 9 32.0 team1-TFIDF_bnn_bnn
3d structure Q0 677 10 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 650 11 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 2339 12 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 528 13 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 646 14 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 2153 15 14.0 team1-TFIDF_bnn_bnn
3d structure Q0 942 16 14.0 team1-TFIDF_bnn_bnn
hyphy Q0 62 0 2.0 team1-TFIDF_bnn_bnn
python Q0 2177 0 32.0 team1-TFIDF_bnn_bnn
python Q0 1016 1 32.0 team1-TFIDF_bnn_bnn
python Q0 709 2 32.0 team1-TFIDF_bnn_bnn
python Q0 307 3 32.0 team1-TFIDF_bnn_bnn
python Q0 882 4 32.0 team1-TFIDF_bnn_bnn
python Q0 2251 5 32.0 team1-TFIDF_bnn_bnn
python Q0 500 6 32.0 team1-TFIDF_bnn_bnn
python Q0 943 7 32.0 team1-TFIDF_bnn_bnn
python Q0 623 8 32.0 team1-TFIDF_bnn_bnn
python Q0 716 9 32.0 team1-TFIDF_bnn_bnn
python Q0 264 10 32.0 team1-TFIDF_bnn_bnn
python Q0 2059 11 32.0 team1-TFIDF_bnn_bnn
python Q0 561 12 32.0 team1-TFIDF_bnn_bnn
python Q0 837 13 32.0 team1-TFIDF_bnn_bnn
python Q0 2128 14 6.0 team1-TFIDF_bnn_bnn
python Q0 1002 15 6.0 team1-TFIDF_bnn_bnn
python Q0 838 16 6.0 team1-TFIDF_bnn_bnn
quantification Q0 774 0 6.0 team1-TFIDF_bnn_bnn
quantification Q0 2056 1 6.0 team1-TFIDF_bnn_bnn
quantification Q0 559 2 4.0 team1-TFIDF_bnn_bnn
quantification Q0 567 3 4.0 team1-TFIDF_bnn_bnn
nanopore Q0 97 0 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 2367 1 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 899 2 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 296 3 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 722 4 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 375 5 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 306 6 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 242 7 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 45 8 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 796 9 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 36 10 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 745 11 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 2306 12 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 2316 13 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 294 14 38.0 team1-TFIDF_bnn_bnn
nanopore Q0 2174 15 10.0 team1-TFIDF_bnn_bnn
nanopore Q0 202 16 10.0 team1-TFIDF_bnn_bnn
nanopore Q0 518 17 10.0 team1-TFIDF_bnn_bnn
nanopore Q0 2145 18 10.0 team1-TFIDF_bnn_bnn
nanopore Q0 452 19 10.0 team1-TFIDF_bnn_bnn
gene Q0 516 0 150.0 team1-TFIDF_bnn_bnn
gene Q0 2062 1 150.0 team1-TFIDF_bnn_bnn
gene Q0 673 2 150.0 team1-TFIDF_bnn_bnn
gene Q0 62 3 150.0 team1-TFIDF_bnn_bnn
gene Q0 193 4 150.0 team1-TFIDF_bnn_bnn
gene Q0 66 5 150.0 team1-TFIDF_bnn_bnn
gene Q0 378 6 150.0 team1-TFIDF_bnn_bnn
gene Q0 194 7 150.0 team1-TFIDF_bnn_bnn
gene Q0 118 8 150.0 team1-TFIDF_bnn_bnn
gene Q0 1012 9 150.0 team1-TFIDF_bnn_bnn
gene Q0 372 10 150.0 team1-TFIDF_bnn_bnn
gene Q0 299 11 150.0 team1-TFIDF_bnn_bnn
gene Q0 70 12 150.0 team1-TFIDF_bnn_bnn
gene Q0 456 13 150.0 team1-TFIDF_bnn_bnn
gene Q0 149 14 150.0 team1-TFIDF_bnn_bnn
gene Q0 997 15 150.0 team1-TFIDF_bnn_bnn
gene Q0 869 16 150.0 team1-TFIDF_bnn_bnn
gene Q0 939 17 150.0 team1-TFIDF_bnn_bnn
gene Q0 481 18 150.0 team1-TFIDF_bnn_bnn
gene Q0 333 19 150.0 team1-TFIDF_bnn_bnn
gene Q0 849 20 150.0 team1-TFIDF_bnn_bnn
gene Q0 687 21 150.0 team1-TFIDF_bnn_bnn
gene Q0 51 22 150.0 team1-TFIDF_bnn_bnn
gene Q0 779 23 150.0 team1-TFIDF_bnn_bnn
gene Q0 153 24 150.0 team1-TFIDF_bnn_bnn
gene Q0 565 25 150.0 team1-TFIDF_bnn_bnn
gene Q0 994 26 150.0 team1-TFIDF_bnn_bnn
gene Q0 693 27 150.0 team1-TFIDF_bnn_bnn
gene Q0 568 28 150.0 team1-TFIDF_bnn_bnn
gene Q0 747 29 150.0 team1-TFIDF_bnn_bnn
gene Q0 367 30 150.0 team1-TFIDF_bnn_bnn
gene Q0 909 31 150.0 team1-TFIDF_bnn_bnn
gene Q0 285 32 150.0 team1-TFIDF_bnn_bnn
gene Q0 57 33 150.0 team1-TFIDF_bnn_bnn
gene Q0 637 34 150.0 team1-TFIDF_bnn_bnn
gene Q0 441 35 150.0 team1-TFIDF_bnn_bnn
gene Q0 161 36 150.0 team1-TFIDF_bnn_bnn
gene Q0 1018 37 150.0 team1-TFIDF_bnn_bnn
gene Q0 777 38 52.0 team1-TFIDF_bnn_bnn
gene Q0 844 39 52.0 team1-TFIDF_bnn_bnn
gene Q0 567 40 52.0 team1-TFIDF_bnn_bnn
gene Q0 595 41 52.0 team1-TFIDF_bnn_bnn
gene Q0 2269 42 52.0 team1-TFIDF_bnn_bnn
gene Q0 522 43 52.0 team1-TFIDF_bnn_bnn
gene Q0 559 44 52.0 team1-TFIDF_bnn_bnn
gene Q0 488 45 52.0 team1-TFIDF_bnn_bnn
gene Q0 2169 46 52.0 team1-TFIDF_bnn_bnn
gene Q0 314 47 52.0 team1-TFIDF_bnn_bnn
gene Q0 2300 48 52.0 team1-TFIDF_bnn_bnn
gene Q0 254 49 52.0 team1-TFIDF_bnn_bnn
classification Q0 306 0 8.0 team1-TFIDF_bnn_bnn
classification Q0 378 1 8.0 team1-TFIDF_bnn_bnn
classification Q0 620 2 8.0 team1-TFIDF_bnn_bnn
classification Q0 702 3 2.0 team1-TFIDF_bnn_bnn
conservation Q0 288 0 4.0 team1-TFIDF_bnn_bnn
conservation Q0 2092 1 4.0 team1-TFIDF_bnn_bnn
conservation Q0 2049 2 4.0 team1-TFIDF_bnn_bnn
sequence homology Q0 388 0 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 5 1 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 125 2 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 294 3 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 378 4 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 935 5 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 705 6 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 882 7 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 765 8 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 452 9 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 837 10 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 620 11 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 107 12 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 45 13 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 70 14 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 741 15 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 228 16 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 847 17 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 732 18 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 303 19 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 815 20 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 722 21 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 595 22 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 561 23 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 343 24 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 91 25 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 159 26 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 289 27 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 817 28 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 225 29 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 818 30 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 51 31 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 103 32 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 692 33 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 703 34 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 375 35 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 570 36 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 802 37 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 950 38 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 242 39 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 62 40 146.0 team1-TFIDF_bnn_bnn
sequence homology Q0 2128 41 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 979 42 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 724 43 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 798 44 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 650 45 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 2156 46 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 110 47 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 2164 48 46.0 team1-TFIDF_bnn_bnn
sequence homology Q0 2043 49 46.0 team1-TFIDF_bnn_bnn
strandedness Q0 2088 0 2.0 team1-TFIDF_bnn_bnn
phylogeny Q0 103 0 6.0 team1-TFIDF_bnn_bnn
phylogeny Q0 1001 1 6.0 team1-TFIDF_bnn_bnn
phylogeny Q0 923 2 2.0 team1-TFIDF_bnn_bnn
indel Q0 705 0 6.0 team1-TFIDF_bnn_bnn
indel Q0 2202 1 6.0 team1-TFIDF_bnn_bnn
indel Q0 2377 2 6.0 team1-TFIDF_bnn_bnn
indel Q0 821 3 6.0 team1-TFIDF_bnn_bnn
indel Q0 449 4 6.0 team1-TFIDF_bnn_bnn
antibiotics Q0 878 0 2.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 774 0 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2056 1 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2298 2 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2194 3 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2165 4 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 884 5 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 372 6 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 540 7 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 924 8 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 703 9 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2242 10 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2215 11 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2119 12 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2140 13 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 584 14 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2088 15 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 969 16 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 333 17 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 395 18 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2068 19 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 46 20 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 278 21 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 232 22 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 238 23 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 57 24 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 524 25 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2101 26 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2199 27 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2356 28 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 1018 29 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 561 30 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 751 31 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 51 32 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 280 33 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 909 34 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 664 35 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 568 36 104.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2282 37 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 518 38 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 528 39 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 942 40 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 771 41 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 2329 42 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 693 43 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 1019 44 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 620 45 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 722 46 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 687 47 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 299 48 34.0 team1-TFIDF_bnn_bnn
chimeric rna Q0 52 49 34.0 team1-TFIDF_bnn_bnn
repeat elements Q0 225 0 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 242 1 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 375 2 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 540 3 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 909 4 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 2275 5 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 2145 6 18.0 team1-TFIDF_bnn_bnn
repeat elements Q0 146 7 4.0 team1-TFIDF_bnn_bnn
repeat elements Q0 945 8 4.0 team1-TFIDF_bnn_bnn
repeat elements Q0 343 9 4.0 team1-TFIDF_bnn_bnn
algorithms Q0 628 0 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 837 1 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 143 2 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 637 3 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 378 4 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 89 5 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 149 6 16.0 team1-TFIDF_bnn_bnn
algorithms Q0 161 7 4.0 team1-TFIDF_bnn_bnn
algorithms Q0 702 8 4.0 team1-TFIDF_bnn_bnn
transcriptome Q0 83 0 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 2036 1 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 703 2 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 584 3 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 2068 4 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 595 5 18.0 team1-TFIDF_bnn_bnn
transcriptome Q0 51 6 6.0 team1-TFIDF_bnn_bnn
transcriptome Q0 46 7 6.0 team1-TFIDF_bnn_bnn
transcriptome Q0 2054 8 6.0 team1-TFIDF_bnn_bnn
granges Q0 2274 0 6.0 team1-TFIDF_bnn_bnn
granges Q0 716 1 6.0 team1-TFIDF_bnn_bnn
granges Q0 2051 2 6.0 team1-TFIDF_bnn_bnn
format conversion Q0 2177 0 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 892 1 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 1019 2 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 1018 3 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2169 4 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 633 5 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 388 6 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 271 7 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 807 8 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 587 9 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 974 10 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 595 11 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 979 12 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 528 13 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 943 14 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2259 15 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 818 16 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 692 17 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 481 18 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 110 19 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 756 20 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 375 21 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 837 22 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 708 23 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2306 24 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 908 25 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2237 26 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 956 27 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 920 28 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 568 29 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2363 30 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 2200 31 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 161 32 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 702 33 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 678 34 92.0 team1-TFIDF_bnn_bnn
format conversion Q0 853 35 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 949 36 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 2156 37 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 1 38 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 884 39 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 488 40 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 661 41 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 565 42 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 2142 43 18.0 team1-TFIDF_bnn_bnn
format conversion Q0 91 44 16.0 team1-TFIDF_bnn_bnn
format conversion Q0 939 45 16.0 team1-TFIDF_bnn_bnn
format conversion Q0 2068 46 16.0 team1-TFIDF_bnn_bnn
format conversion Q0 522 47 16.0 team1-TFIDF_bnn_bnn
format conversion Q0 525 48 16.0 team1-TFIDF_bnn_bnn
format conversion Q0 694 49 16.0 team1-TFIDF_bnn_bnn
hgp Q0 5 0 2.0 team1-TFIDF_bnn_bnn
illumina Q0 449 0 32.0 team1-TFIDF_bnn_bnn
illumina Q0 2081 1 32.0 team1-TFIDF_bnn_bnn
illumina Q0 357 2 32.0 team1-TFIDF_bnn_bnn
illumina Q0 120 3 32.0 team1-TFIDF_bnn_bnn
illumina Q0 407 4 32.0 team1-TFIDF_bnn_bnn
illumina Q0 438 5 32.0 team1-TFIDF_bnn_bnn
illumina Q0 2293 6 32.0 team1-TFIDF_bnn_bnn
illumina Q0 242 7 32.0 team1-TFIDF_bnn_bnn
illumina Q0 329 8 32.0 team1-TFIDF_bnn_bnn
illumina Q0 2149 9 32.0 team1-TFIDF_bnn_bnn
illumina Q0 2216 10 32.0 team1-TFIDF_bnn_bnn
illumina Q0 2119 11 32.0 team1-TFIDF_bnn_bnn
illumina Q0 418 12 32.0 team1-TFIDF_bnn_bnn
illumina Q0 761 13 6.0 team1-TFIDF_bnn_bnn
illumina Q0 654 14 6.0 team1-TFIDF_bnn_bnn
illumina Q0 2333 15 6.0 team1-TFIDF_bnn_bnn
k mer Q0 146 0 22.0 team1-TFIDF_bnn_bnn
k mer Q0 51 1 22.0 team1-TFIDF_bnn_bnn
k mer Q0 2237 2 22.0 team1-TFIDF_bnn_bnn
k mer Q0 2174 3 22.0 team1-TFIDF_bnn_bnn
k mer Q0 561 4 14.0 team1-TFIDF_bnn_bnn
k mer Q0 702 5 14.0 team1-TFIDF_bnn_bnn
k mer Q0 2390 6 14.0 team1-TFIDF_bnn_bnn
k mer Q0 709 7 14.0 team1-TFIDF_bnn_bnn
k mer Q0 19 8 14.0 team1-TFIDF_bnn_bnn
k mer Q0 2152 9 4.0 team1-TFIDF_bnn_bnn
k mer Q0 2142 10 4.0 team1-TFIDF_bnn_bnn
maf Q0 2242 0 4.0 team1-TFIDF_bnn_bnn
maf Q0 317 1 2.0 team1-TFIDF_bnn_bnn
pysam Q0 2149 0 8.0 team1-TFIDF_bnn_bnn
pysam Q0 280 1 8.0 team1-TFIDF_bnn_bnn
pysam Q0 2131 2 4.0 team1-TFIDF_bnn_bnn
pysam Q0 2163 3 4.0 team1-TFIDF_bnn_bnn
hg18 Q0 316 0 4.0 team1-TFIDF_bnn_bnn
hg18 Q0 318 1 4.0 team1-TFIDF_bnn_bnn
yield Q0 296 0 2.0 team1-TFIDF_bnn_bnn
fcs Q0 956 0 2.0 team1-TFIDF_bnn_bnn
vcf Q0 837 0 40.0 team1-TFIDF_bnn_bnn
vcf Q0 842 1 40.0 team1-TFIDF_bnn_bnn
vcf Q0 661 2 40.0 team1-TFIDF_bnn_bnn
vcf Q0 856 3 40.0 team1-TFIDF_bnn_bnn
vcf Q0 462 4 40.0 team1-TFIDF_bnn_bnn
vcf Q0 285 5 40.0 team1-TFIDF_bnn_bnn
vcf Q0 752 6 28.0 team1-TFIDF_bnn_bnn
vcf Q0 2223 7 28.0 team1-TFIDF_bnn_bnn
vcf Q0 271 8 28.0 team1-TFIDF_bnn_bnn
vcf Q0 974 9 28.0 team1-TFIDF_bnn_bnn
vcf Q0 654 10 28.0 team1-TFIDF_bnn_bnn
vcf Q0 344 11 28.0 team1-TFIDF_bnn_bnn
vcf Q0 481 12 28.0 team1-TFIDF_bnn_bnn
vcf Q0 672 13 28.0 team1-TFIDF_bnn_bnn
vcf Q0 168 14 28.0 team1-TFIDF_bnn_bnn
vcf Q0 2279 15 28.0 team1-TFIDF_bnn_bnn
vcf Q0 949 16 28.0 team1-TFIDF_bnn_bnn
vcf Q0 2275 17 28.0 team1-TFIDF_bnn_bnn
vcf Q0 769 18 28.0 team1-TFIDF_bnn_bnn
vcf Q0 264 19 28.0 team1-TFIDF_bnn_bnn
go enrichment Q0 769 0 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 962 1 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 817 2 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2323 3 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 584 4 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2059 5 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2333 6 24.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2073 7 18.0 team1-TFIDF_bnn_bnn
go enrichment Q0 230 8 18.0 team1-TFIDF_bnn_bnn
go enrichment Q0 1012 9 18.0 team1-TFIDF_bnn_bnn
go enrichment Q0 149 10 18.0 team1-TFIDF_bnn_bnn
go enrichment Q0 568 11 18.0 team1-TFIDF_bnn_bnn
go enrichment Q0 254 12 8.0 team1-TFIDF_bnn_bnn
go enrichment Q0 314 13 8.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2346 14 8.0 team1-TFIDF_bnn_bnn
go enrichment Q0 2343 15 8.0 team1-TFIDF_bnn_bnn
medips Q0 2028 0 2.0 team1-TFIDF_bnn_bnn
multi sample Q0 2048 0 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2310 1 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 970 2 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 664 3 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 627 4 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 692 5 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 951 6 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2265 7 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2361 8 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 271 9 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2140 10 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2097 11 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 238 12 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 318 13 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 869 14 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 36 15 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 611 16 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 609 17 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 481 18 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 351 19 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2194 20 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 97 21 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 962 22 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2119 23 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 19 24 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 83 25 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2199 26 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 2324 27 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 1002 28 68.0 team1-TFIDF_bnn_bnn
multi sample Q0 280 29 12.0 team1-TFIDF_bnn_bnn
multi sample Q0 769 30 12.0 team1-TFIDF_bnn_bnn
multi sample Q0 2101 31 12.0 team1-TFIDF_bnn_bnn
multi sample Q0 388 32 12.0 team1-TFIDF_bnn_bnn
multi sample Q0 73 33 10.0 team1-TFIDF_bnn_bnn
multi sample Q0 316 34 10.0 team1-TFIDF_bnn_bnn
multi sample Q0 251 35 10.0 team1-TFIDF_bnn_bnn
multi sample Q0 779 36 10.0 team1-TFIDF_bnn_bnn
multi sample Q0 761 37 10.0 team1-TFIDF_bnn_bnn
multi sample Q0 283 38 4.0 team1-TFIDF_bnn_bnn
multi sample Q0 434 39 4.0 team1-TFIDF_bnn_bnn
homology modelling Q0 2339 0 4.0 team1-TFIDF_bnn_bnn
homology modelling Q0 191 1 4.0 team1-TFIDF_bnn_bnn
multi omics Q0 769 0 12.0 team1-TFIDF_bnn_bnn
multi omics Q0 388 1 12.0 team1-TFIDF_bnn_bnn
multi omics Q0 73 2 12.0 team1-TFIDF_bnn_bnn
multi omics Q0 2101 3 12.0 team1-TFIDF_bnn_bnn
multi omics Q0 280 4 12.0 team1-TFIDF_bnn_bnn
multi omics Q0 886 5 6.0 team1-TFIDF_bnn_bnn
multi omics Q0 283 6 4.0 team1-TFIDF_bnn_bnn
multi omics Q0 434 7 4.0 team1-TFIDF_bnn_bnn
multi omics Q0 2113 8 4.0 team1-TFIDF_bnn_bnn
featurecounts Q0 2101 0 2.0 team1-TFIDF_bnn_bnn
drugs Q0 756 0 8.0 team1-TFIDF_bnn_bnn
drugs Q0 750 1 8.0 team1-TFIDF_bnn_bnn
drugs Q0 9 2 8.0 team1-TFIDF_bnn_bnn
drugs Q0 633 3 4.0 team1-TFIDF_bnn_bnn
drugs Q0 2029 4 4.0 team1-TFIDF_bnn_bnn
homework Q0 765 0 2.0 team1-TFIDF_bnn_bnn
reproducibility Q0 112 0 2.0 team1-TFIDF_bnn_bnn
orthology Q0 1012 0 4.0 team1-TFIDF_bnn_bnn
orthology Q0 165 1 4.0 team1-TFIDF_bnn_bnn
identifiers Q0 2343 0 4.0 team1-TFIDF_bnn_bnn
identifiers Q0 488 1 4.0 team1-TFIDF_bnn_bnn
ucsc Q0 322 0 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 895 1 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 2083 2 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 27 3 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 249 4 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 2117 5 14.0 team1-TFIDF_bnn_bnn
ucsc Q0 2237 6 2.0 team1-TFIDF_bnn_bnn
open data Q0 9 0 266.0 team1-TFIDF_bnn_bnn
open data Q0 395 1 266.0 team1-TFIDF_bnn_bnn
open data Q0 29 2 266.0 team1-TFIDF_bnn_bnn
open data Q0 57 3 266.0 team1-TFIDF_bnn_bnn
open data Q0 481 4 266.0 team1-TFIDF_bnn_bnn
open data Q0 609 5 266.0 team1-TFIDF_bnn_bnn
open data Q0 610 6 266.0 team1-TFIDF_bnn_bnn
open data Q0 103 7 266.0 team1-TFIDF_bnn_bnn
open data Q0 627 8 266.0 team1-TFIDF_bnn_bnn
open data Q0 232 9 266.0 team1-TFIDF_bnn_bnn
open data Q0 488 10 266.0 team1-TFIDF_bnn_bnn
open data Q0 418 11 266.0 team1-TFIDF_bnn_bnn
open data Q0 66 12 266.0 team1-TFIDF_bnn_bnn
open data Q0 242 13 266.0 team1-TFIDF_bnn_bnn
open data Q0 626 14 266.0 team1-TFIDF_bnn_bnn
open data Q0 19 15 266.0 team1-TFIDF_bnn_bnn
open data Q0 294 16 266.0 team1-TFIDF_bnn_bnn
open data Q0 195 17 266.0 team1-TFIDF_bnn_bnn
open data Q0 372 18 266.0 team1-TFIDF_bnn_bnn
open data Q0 196 19 266.0 team1-TFIDF_bnn_bnn
open data Q0 452 20 266.0 team1-TFIDF_bnn_bnn
open data Q0 328 21 266.0 team1-TFIDF_bnn_bnn
open data Q0 282 22 266.0 team1-TFIDF_bnn_bnn
open data Q0 308 23 266.0 team1-TFIDF_bnn_bnn
open data Q0 584 24 266.0 team1-TFIDF_bnn_bnn
open data Q0 73 25 266.0 team1-TFIDF_bnn_bnn
open data Q0 83 26 266.0 team1-TFIDF_bnn_bnn
open data Q0 283 27 266.0 team1-TFIDF_bnn_bnn
open data Q0 565 28 266.0 team1-TFIDF_bnn_bnn
open data Q0 343 29 266.0 team1-TFIDF_bnn_bnn
open data Q0 89 30 266.0 team1-TFIDF_bnn_bnn
open data Q0 92 31 266.0 team1-TFIDF_bnn_bnn
open data Q0 567 32 266.0 team1-TFIDF_bnn_bnn
open data Q0 351 33 266.0 team1-TFIDF_bnn_bnn
open data Q0 462 34 78.0 team1-TFIDF_bnn_bnn
open data Q0 112 35 78.0 team1-TFIDF_bnn_bnn
open data Q0 899 36 78.0 team1-TFIDF_bnn_bnn
open data Q0 120 37 78.0 team1-TFIDF_bnn_bnn
open data Q0 771 38 78.0 team1-TFIDF_bnn_bnn
open data Q0 2361 39 78.0 team1-TFIDF_bnn_bnn
open data Q0 456 40 78.0 team1-TFIDF_bnn_bnn
open data Q0 434 41 78.0 team1-TFIDF_bnn_bnn
open data Q0 756 42 78.0 team1-TFIDF_bnn_bnn
open data Q0 1014 43 78.0 team1-TFIDF_bnn_bnn
open data Q0 253 44 78.0 team1-TFIDF_bnn_bnn
open data Q0 505 45 78.0 team1-TFIDF_bnn_bnn
open data Q0 702 46 78.0 team1-TFIDF_bnn_bnn
open data Q0 2289 47 78.0 team1-TFIDF_bnn_bnn
open data Q0 2065 48 78.0 team1-TFIDF_bnn_bnn
open data Q0 414 49 78.0 team1-TFIDF_bnn_bnn
computation Q0 361 0 8.0 team1-TFIDF_bnn_bnn
computation Q0 716 1 8.0 team1-TFIDF_bnn_bnn
computation Q0 441 2 8.0 team1-TFIDF_bnn_bnn
computation Q0 2234 3 2.0 team1-TFIDF_bnn_bnn
read alignment Q0 134 0 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 518 1 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 524 2 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 280 3 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 174 4 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 608 5 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 942 6 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 610 7 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 943 8 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 153 9 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 307 10 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 745 11 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 282 12 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 308 13 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 157 14 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 438 15 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 694 16 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 372 17 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 702 18 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 761 19 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 253 20 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 637 21 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 639 22 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 404 23 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 452 24 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 456 25 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 73 26 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 424 27 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 716 28 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 336 29 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 83 30 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 731 31 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 223 32 152.0 team1-TFIDF_bnn_bnn
read alignment Q0 1018 33 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 191 34 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 705 35 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 736 36 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 396 37 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 98 38 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 994 39 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 228 40 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 357 41 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 103 42 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 2186 43 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 1001 44 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 626 45 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 289 46 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 2034 47 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 2202 48 80.0 team1-TFIDF_bnn_bnn
read alignment Q0 1010 49 80.0 team1-TFIDF_bnn_bnn
genome Q0 1 0 166.0 team1-TFIDF_bnn_bnn
genome Q0 774 1 166.0 team1-TFIDF_bnn_bnn
genome Q0 375 2 166.0 team1-TFIDF_bnn_bnn
genome Q0 527 3 166.0 team1-TFIDF_bnn_bnn
genome Q0 288 4 166.0 team1-TFIDF_bnn_bnn
genome Q0 107 5 166.0 team1-TFIDF_bnn_bnn
genome Q0 442 6 166.0 team1-TFIDF_bnn_bnn
genome Q0 316 7 166.0 team1-TFIDF_bnn_bnn
genome Q0 702 8 166.0 team1-TFIDF_bnn_bnn
genome Q0 418 9 166.0 team1-TFIDF_bnn_bnn
genome Q0 449 10 166.0 team1-TFIDF_bnn_bnn
genome Q0 195 11 166.0 team1-TFIDF_bnn_bnn
genome Q0 608 12 166.0 team1-TFIDF_bnn_bnn
genome Q0 709 13 166.0 team1-TFIDF_bnn_bnn
genome Q0 404 14 166.0 team1-TFIDF_bnn_bnn
genome Q0 807 15 166.0 team1-TFIDF_bnn_bnn
genome Q0 328 16 166.0 team1-TFIDF_bnn_bnn
genome Q0 462 17 166.0 team1-TFIDF_bnn_bnn
genome Q0 604 18 166.0 team1-TFIDF_bnn_bnn
genome Q0 351 19 166.0 team1-TFIDF_bnn_bnn
genome Q0 135 20 166.0 team1-TFIDF_bnn_bnn
genome Q0 27 21 166.0 team1-TFIDF_bnn_bnn
genome Q0 736 22 166.0 team1-TFIDF_bnn_bnn
genome Q0 481 23 166.0 team1-TFIDF_bnn_bnn
genome Q0 817 24 166.0 team1-TFIDF_bnn_bnn
genome Q0 565 25 166.0 team1-TFIDF_bnn_bnn
genome Q0 796 26 166.0 team1-TFIDF_bnn_bnn
genome Q0 438 27 166.0 team1-TFIDF_bnn_bnn
genome Q0 628 28 166.0 team1-TFIDF_bnn_bnn
genome Q0 120 29 166.0 team1-TFIDF_bnn_bnn
genome Q0 285 30 166.0 team1-TFIDF_bnn_bnn
genome Q0 568 31 166.0 team1-TFIDF_bnn_bnn
genome Q0 322 32 52.0 team1-TFIDF_bnn_bnn
genome Q0 540 33 52.0 team1-TFIDF_bnn_bnn
genome Q0 303 34 52.0 team1-TFIDF_bnn_bnn
genome Q0 901 35 52.0 team1-TFIDF_bnn_bnn
genome Q0 343 36 52.0 team1-TFIDF_bnn_bnn
genome Q0 5 37 52.0 team1-TFIDF_bnn_bnn
genome Q0 990 38 52.0 team1-TFIDF_bnn_bnn
genome Q0 46 39 52.0 team1-TFIDF_bnn_bnn
genome Q0 225 40 52.0 team1-TFIDF_bnn_bnn
genome Q0 2274 41 52.0 team1-TFIDF_bnn_bnn
genome Q0 242 42 52.0 team1-TFIDF_bnn_bnn
genome Q0 821 43 52.0 team1-TFIDF_bnn_bnn
genome Q0 2361 44 52.0 team1-TFIDF_bnn_bnn
genome Q0 518 45 52.0 team1-TFIDF_bnn_bnn
genome Q0 785 46 52.0 team1-TFIDF_bnn_bnn
genome Q0 36 47 52.0 team1-TFIDF_bnn_bnn
genome Q0 168 48 52.0 team1-TFIDF_bnn_bnn
genome Q0 2216 49 52.0 team1-TFIDF_bnn_bnn
single cell Q0 2049 0 82.0 team1-TFIDF_bnn_bnn
single cell Q0 908 1 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2201 2 82.0 team1-TFIDF_bnn_bnn
single cell Q0 540 3 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2230 4 82.0 team1-TFIDF_bnn_bnn
single cell Q0 951 5 82.0 team1-TFIDF_bnn_bnn
single cell Q0 568 6 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2361 7 82.0 team1-TFIDF_bnn_bnn
single cell Q0 165 8 82.0 team1-TFIDF_bnn_bnn
single cell Q0 314 9 82.0 team1-TFIDF_bnn_bnn
single cell Q0 954 10 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2065 11 82.0 team1-TFIDF_bnn_bnn
single cell Q0 807 12 82.0 team1-TFIDF_bnn_bnn
single cell Q0 990 13 82.0 team1-TFIDF_bnn_bnn
single cell Q0 318 14 82.0 team1-TFIDF_bnn_bnn
single cell Q0 595 15 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2194 16 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2215 17 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2088 18 82.0 team1-TFIDF_bnn_bnn
single cell Q0 722 19 82.0 team1-TFIDF_bnn_bnn
single cell Q0 388 20 82.0 team1-TFIDF_bnn_bnn
single cell Q0 19 21 82.0 team1-TFIDF_bnn_bnn
single cell Q0 174 22 82.0 team1-TFIDF_bnn_bnn
single cell Q0 853 23 82.0 team1-TFIDF_bnn_bnn
single cell Q0 232 24 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2153 25 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2199 26 82.0 team1-TFIDF_bnn_bnn
single cell Q0 565 27 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2169 28 82.0 team1-TFIDF_bnn_bnn
single cell Q0 125 29 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2101 30 82.0 team1-TFIDF_bnn_bnn
single cell Q0 2174 31 82.0 team1-TFIDF_bnn_bnn
single cell Q0 306 32 44.0 team1-TFIDF_bnn_bnn
single cell Q0 765 33 44.0 team1-TFIDF_bnn_bnn
single cell Q0 2310 34 44.0 team1-TFIDF_bnn_bnn
single cell Q0 2356 35 44.0 team1-TFIDF_bnn_bnn
single cell Q0 441 36 44.0 team1-TFIDF_bnn_bnn
single cell Q0 29 37 44.0 team1-TFIDF_bnn_bnn
single cell Q0 779 38 44.0 team1-TFIDF_bnn_bnn
single cell Q0 2241 39 44.0 team1-TFIDF_bnn_bnn
single cell Q0 584 40 44.0 team1-TFIDF_bnn_bnn
single cell Q0 46 41 44.0 team1-TFIDF_bnn_bnn
single cell Q0 750 42 44.0 team1-TFIDF_bnn_bnn
single cell Q0 395 43 44.0 team1-TFIDF_bnn_bnn
single cell Q0 278 44 20.0 team1-TFIDF_bnn_bnn
single cell Q0 249 45 20.0 team1-TFIDF_bnn_bnn
single cell Q0 777 46 20.0 team1-TFIDF_bnn_bnn
single cell Q0 771 47 20.0 team1-TFIDF_bnn_bnn
single cell Q0 2109 48 20.0 team1-TFIDF_bnn_bnn
single cell Q0 693 49 20.0 team1-TFIDF_bnn_bnn
deeptools Q0 608 0 6.0 team1-TFIDF_bnn_bnn
deeptools Q0 525 1 6.0 team1-TFIDF_bnn_bnn
deeptools Q0 708 2 6.0 team1-TFIDF_bnn_bnn
exome Q0 316 0 8.0 team1-TFIDF_bnn_bnn
exome Q0 351 1 8.0 team1-TFIDF_bnn_bnn
exome Q0 672 2 4.0 team1-TFIDF_bnn_bnn
exome Q0 427 3 4.0 team1-TFIDF_bnn_bnn
snp Q0 336 0 12.0 team1-TFIDF_bnn_bnn
snp Q0 89 1 12.0 team1-TFIDF_bnn_bnn
snp Q0 73 2 12.0 team1-TFIDF_bnn_bnn
snp Q0 407 3 12.0 team1-TFIDF_bnn_bnn
snp Q0 705 4 12.0 team1-TFIDF_bnn_bnn
snp Q0 2352 5 12.0 team1-TFIDF_bnn_bnn
scaffold Q0 97 0 4.0 team1-TFIDF_bnn_bnn
scaffold Q0 2149 1 4.0 team1-TFIDF_bnn_bnn
report Q0 945 0 12.0 team1-TFIDF_bnn_bnn
report Q0 908 1 12.0 team1-TFIDF_bnn_bnn
report Q0 2083 2 12.0 team1-TFIDF_bnn_bnn
report Q0 424 3 12.0 team1-TFIDF_bnn_bnn
report Q0 853 4 12.0 team1-TFIDF_bnn_bnn
report Q0 524 5 2.0 team1-TFIDF_bnn_bnn
reference genome Q0 1 0 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 135 1 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 375 2 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 628 3 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 404 4 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 807 5 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 328 6 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 462 7 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 604 8 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 351 9 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 608 10 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 736 11 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 481 12 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 27 13 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 817 14 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 107 15 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 796 16 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 565 17 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 438 18 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 568 19 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 120 20 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 774 21 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 285 22 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 442 23 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 316 24 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 288 25 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 702 26 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 449 27 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 527 28 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 418 29 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 195 30 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 709 31 166.0 team1-TFIDF_bnn_bnn
reference genome Q0 719 32 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 1012 33 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 979 34 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 336 35 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 747 36 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 769 37 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 705 38 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 153 39 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 945 40 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 908 41 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 869 42 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 818 43 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 103 44 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 2031 45 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 525 46 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 271 47 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 672 48 128.0 team1-TFIDF_bnn_bnn
reference genome Q0 321 49 128.0 team1-TFIDF_bnn_bnn
snv Q0 2275 0 2.0 team1-TFIDF_bnn_bnn
statistics Q0 242 0 14.0 team1-TFIDF_bnn_bnn
statistics Q0 765 1 14.0 team1-TFIDF_bnn_bnn
statistics Q0 627 2 14.0 team1-TFIDF_bnn_bnn
statistics Q0 361 3 14.0 team1-TFIDF_bnn_bnn
statistics Q0 103 4 14.0 team1-TFIDF_bnn_bnn
statistics Q0 2204 5 14.0 team1-TFIDF_bnn_bnn
statistics Q0 678 6 2.0 team1-TFIDF_bnn_bnn
data retrieval Q0 9 0 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 19 1 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 418 2 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 66 3 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 242 4 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 626 5 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 627 6 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 195 7 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 372 8 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 294 9 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 196 10 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 452 11 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 328 12 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 282 13 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 584 14 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 488 15 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 73 16 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 103 17 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 308 18 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 609 19 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 83 20 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 395 21 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 283 22 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 565 23 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 343 24 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 89 25 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 92 26 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 567 27 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 351 28 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 481 29 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 29 30 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 57 31 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 610 32 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 232 33 266.0 team1-TFIDF_bnn_bnn
data retrieval Q0 456 34 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 299 35 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 2117 36 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 253 37 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 278 38 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 899 39 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 1014 40 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 505 41 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 771 42 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 191 43 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 702 44 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 458 45 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 462 46 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 2202 47 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 97 48 78.0 team1-TFIDF_bnn_bnn
data retrieval Q0 350 49 78.0 team1-TFIDF_bnn_bnn
macs2 Q0 161 0 2.0 team1-TFIDF_bnn_bnn
chip seq Q0 2051 0 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2179 1 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2300 2 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 774 3 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 909 4 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2119 5 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2165 6 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 584 7 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 751 8 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 238 9 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 540 10 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 969 11 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2194 12 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2215 13 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 83 14 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2068 15 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2088 16 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 228 17 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 232 18 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 661 19 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2028 20 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 561 21 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 524 22 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 278 23 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2242 24 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 960 25 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 703 26 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 51 27 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2101 28 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2043 29 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 372 30 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2298 31 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 2199 32 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 280 33 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 695 34 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 664 35 106.0 team1-TFIDF_bnn_bnn
chip seq Q0 687 36 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 414 37 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 1014 38 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 693 39 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 620 40 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 722 41 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 2329 42 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 771 43 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 2378 44 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 92 45 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 2282 46 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 395 47 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 610 48 36.0 team1-TFIDF_bnn_bnn
chip seq Q0 253 49 36.0 team1-TFIDF_bnn_bnn
kegg Q0 1012 0 10.0 team1-TFIDF_bnn_bnn
kegg Q0 878 1 10.0 team1-TFIDF_bnn_bnn
kegg Q0 844 2 10.0 team1-TFIDF_bnn_bnn
kegg Q0 230 3 4.0 team1-TFIDF_bnn_bnn
kegg Q0 165 4 4.0 team1-TFIDF_bnn_bnn
smalt Q0 308 0 2.0 team1-TFIDF_bnn_bnn
threshold Q0 288 0 18.0 team1-TFIDF_bnn_bnn
threshold Q0 110 1 18.0 team1-TFIDF_bnn_bnn
threshold Q0 909 2 18.0 team1-TFIDF_bnn_bnn
threshold Q0 317 3 18.0 team1-TFIDF_bnn_bnn
threshold Q0 2092 4 18.0 team1-TFIDF_bnn_bnn
threshold Q0 731 5 18.0 team1-TFIDF_bnn_bnn
threshold Q0 314 6 18.0 team1-TFIDF_bnn_bnn
threshold Q0 2073 7 18.0 team1-TFIDF_bnn_bnn
threshold Q0 194 8 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 288 0 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 1 1 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 388 2 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 5 3 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 528 4 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 2203 5 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 196 6 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 997 7 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 1019 8 20.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 2140 9 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 125 10 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 782 11 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 350 12 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 378 13 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 70 14 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 89 15 18.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 159 16 6.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 57 17 6.0 team1-TFIDF_bnn_bnn
nucleotide models Q0 877 18 6.0 team1-TFIDF_bnn_bnn
minion Q0 2145 0 26.0 team1-TFIDF_bnn_bnn
minion Q0 2367 1 26.0 team1-TFIDF_bnn_bnn
minion Q0 2306 2 26.0 team1-TFIDF_bnn_bnn
minion Q0 732 3 26.0 team1-TFIDF_bnn_bnn
minion Q0 36 4 26.0 team1-TFIDF_bnn_bnn
minion Q0 45 5 26.0 team1-TFIDF_bnn_bnn
minion Q0 306 6 26.0 team1-TFIDF_bnn_bnn
minion Q0 518 7 26.0 team1-TFIDF_bnn_bnn
minion Q0 2359 8 26.0 team1-TFIDF_bnn_bnn
minion Q0 2174 9 26.0 team1-TFIDF_bnn_bnn
minion Q0 296 10 10.0 team1-TFIDF_bnn_bnn
minion Q0 438 11 10.0 team1-TFIDF_bnn_bnn
minion Q0 899 12 10.0 team1-TFIDF_bnn_bnn
minion Q0 745 13 10.0 team1-TFIDF_bnn_bnn
minion Q0 294 14 10.0 team1-TFIDF_bnn_bnn
gtools Q0 317 0 2.0 team1-TFIDF_bnn_bnn
reference Q0 769 0 128.0 team1-TFIDF_bnn_bnn
reference Q0 2051 1 128.0 team1-TFIDF_bnn_bnn
reference Q0 271 2 128.0 team1-TFIDF_bnn_bnn
reference Q0 285 3 128.0 team1-TFIDF_bnn_bnn
reference Q0 452 4 128.0 team1-TFIDF_bnn_bnn
reference Q0 242 5 128.0 team1-TFIDF_bnn_bnn
reference Q0 2031 6 128.0 team1-TFIDF_bnn_bnn
reference Q0 747 7 128.0 team1-TFIDF_bnn_bnn
reference Q0 837 8 128.0 team1-TFIDF_bnn_bnn
reference Q0 869 9 128.0 team1-TFIDF_bnn_bnn
reference Q0 838 10 128.0 team1-TFIDF_bnn_bnn
reference Q0 527 11 128.0 team1-TFIDF_bnn_bnn
reference Q0 672 12 128.0 team1-TFIDF_bnn_bnn
reference Q0 608 13 128.0 team1-TFIDF_bnn_bnn
reference Q0 990 14 128.0 team1-TFIDF_bnn_bnn
reference Q0 604 15 128.0 team1-TFIDF_bnn_bnn
reference Q0 289 16 128.0 team1-TFIDF_bnn_bnn
reference Q0 719 17 128.0 team1-TFIDF_bnn_bnn
reference Q0 336 18 128.0 team1-TFIDF_bnn_bnn
reference Q0 908 19 128.0 team1-TFIDF_bnn_bnn
reference Q0 2065 20 128.0 team1-TFIDF_bnn_bnn
reference Q0 979 21 128.0 team1-TFIDF_bnn_bnn
reference Q0 678 22 128.0 team1-TFIDF_bnn_bnn
reference Q0 404 23 128.0 team1-TFIDF_bnn_bnn
reference Q0 807 24 128.0 team1-TFIDF_bnn_bnn
reference Q0 705 25 128.0 team1-TFIDF_bnn_bnn
reference Q0 449 26 128.0 team1-TFIDF_bnn_bnn
reference Q0 321 27 128.0 team1-TFIDF_bnn_bnn
reference Q0 481 28 128.0 team1-TFIDF_bnn_bnn
reference Q0 120 29 128.0 team1-TFIDF_bnn_bnn
reference Q0 1012 30 128.0 team1-TFIDF_bnn_bnn
reference Q0 818 31 128.0 team1-TFIDF_bnn_bnn
reference Q0 103 32 128.0 team1-TFIDF_bnn_bnn
reference Q0 525 33 128.0 team1-TFIDF_bnn_bnn
reference Q0 153 34 128.0 team1-TFIDF_bnn_bnn
reference Q0 945 35 128.0 team1-TFIDF_bnn_bnn
reference Q0 821 36 128.0 team1-TFIDF_bnn_bnn
reference Q0 654 37 128.0 team1-TFIDF_bnn_bnn
reference Q0 540 38 128.0 team1-TFIDF_bnn_bnn
reference Q0 796 39 128.0 team1-TFIDF_bnn_bnn
reference Q0 27 40 30.0 team1-TFIDF_bnn_bnn
reference Q0 97 41 30.0 team1-TFIDF_bnn_bnn
reference Q0 2223 42 30.0 team1-TFIDF_bnn_bnn
reference Q0 2036 43 30.0 team1-TFIDF_bnn_bnn
reference Q0 396 44 30.0 team1-TFIDF_bnn_bnn
reference Q0 2204 45 30.0 team1-TFIDF_bnn_bnn
reference Q0 326 46 30.0 team1-TFIDF_bnn_bnn
reference Q0 36 47 30.0 team1-TFIDF_bnn_bnn
reference Q0 2034 48 30.0 team1-TFIDF_bnn_bnn
reference Q0 901 49 30.0 team1-TFIDF_bnn_bnn
pacbio Q0 1010 0 14.0 team1-TFIDF_bnn_bnn
pacbio Q0 899 1 14.0 team1-TFIDF_bnn_bnn
pacbio Q0 438 2 14.0 team1-TFIDF_bnn_bnn
pacbio Q0 375 3 14.0 team1-TFIDF_bnn_bnn
pacbio Q0 174 4 14.0 team1-TFIDF_bnn_bnn
pacbio Q0 885 5 4.0 team1-TFIDF_bnn_bnn
pacbio Q0 329 6 4.0 team1-TFIDF_bnn_bnn
fluorescence Q0 434 0 2.0 team1-TFIDF_bnn_bnn
rna structure Q0 774 0 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 395 1 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2298 2 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 524 3 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2199 4 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2356 5 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 884 6 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 372 7 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2165 8 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 751 9 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 1018 10 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 280 11 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2101 12 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 664 13 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 568 14 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 57 15 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 540 16 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 924 17 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2140 18 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 703 19 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2242 20 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2119 21 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 584 22 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 969 23 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2056 24 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2194 25 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2215 26 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 333 27 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2088 28 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 46 29 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 232 30 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 2068 31 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 238 32 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 278 33 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 561 34 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 51 35 104.0 team1-TFIDF_bnn_bnn
rna structure Q0 1019 36 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 52 37 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 693 38 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 620 39 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 687 40 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 518 41 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 2329 42 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 92 43 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 299 44 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 771 45 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 722 46 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 610 47 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 570 48 34.0 team1-TFIDF_bnn_bnn
rna structure Q0 2282 49 34.0 team1-TFIDF_bnn_bnn
gff3 Q0 2177 0 14.0 team1-TFIDF_bnn_bnn
gff3 Q0 565 1 14.0 team1-TFIDF_bnn_bnn
gff3 Q0 661 2 14.0 team1-TFIDF_bnn_bnn
gff3 Q0 853 3 10.0 team1-TFIDF_bnn_bnn
gff3 Q0 2095 4 10.0 team1-TFIDF_bnn_bnn
gff3 Q0 2242 5 10.0 team1-TFIDF_bnn_bnn
gff3 Q0 2068 6 10.0 team1-TFIDF_bnn_bnn
gff3 Q0 2341 7 10.0 team1-TFIDF_bnn_bnn
wgs Q0 945 0 14.0 team1-TFIDF_bnn_bnn
wgs Q0 191 1 14.0 team1-TFIDF_bnn_bnn
wgs Q0 407 2 14.0 team1-TFIDF_bnn_bnn
wgs Q0 411 3 14.0 team1-TFIDF_bnn_bnn
wgs Q0 951 4 14.0 team1-TFIDF_bnn_bnn
wgs Q0 935 5 14.0 team1-TFIDF_bnn_bnn
wgs Q0 462 6 4.0 team1-TFIDF_bnn_bnn
wgs Q0 299 7 4.0 team1-TFIDF_bnn_bnn
rna Q0 774 0 104.0 team1-TFIDF_bnn_bnn
rna Q0 2056 1 104.0 team1-TFIDF_bnn_bnn
rna Q0 2298 2 104.0 team1-TFIDF_bnn_bnn
rna Q0 2194 3 104.0 team1-TFIDF_bnn_bnn
rna Q0 2165 4 104.0 team1-TFIDF_bnn_bnn
rna Q0 884 5 104.0 team1-TFIDF_bnn_bnn
rna Q0 372 6 104.0 team1-TFIDF_bnn_bnn
rna Q0 540 7 104.0 team1-TFIDF_bnn_bnn
rna Q0 924 8 104.0 team1-TFIDF_bnn_bnn
rna Q0 703 9 104.0 team1-TFIDF_bnn_bnn
rna Q0 2242 10 104.0 team1-TFIDF_bnn_bnn
rna Q0 2215 11 104.0 team1-TFIDF_bnn_bnn
rna Q0 2119 12 104.0 team1-TFIDF_bnn_bnn
rna Q0 2140 13 104.0 team1-TFIDF_bnn_bnn
rna Q0 584 14 104.0 team1-TFIDF_bnn_bnn
rna Q0 2088 15 104.0 team1-TFIDF_bnn_bnn
rna Q0 969 16 104.0 team1-TFIDF_bnn_bnn
rna Q0 333 17 104.0 team1-TFIDF_bnn_bnn
rna Q0 395 18 104.0 team1-TFIDF_bnn_bnn
rna Q0 2068 19 104.0 team1-TFIDF_bnn_bnn
rna Q0 46 20 104.0 team1-TFIDF_bnn_bnn
rna Q0 278 21 104.0 team1-TFIDF_bnn_bnn
rna Q0 232 22 104.0 team1-TFIDF_bnn_bnn
rna Q0 238 23 104.0 team1-TFIDF_bnn_bnn
rna Q0 57 24 104.0 team1-TFIDF_bnn_bnn
rna Q0 524 25 104.0 team1-TFIDF_bnn_bnn
rna Q0 2101 26 104.0 team1-TFIDF_bnn_bnn
rna Q0 2199 27 104.0 team1-TFIDF_bnn_bnn
rna Q0 2356 28 104.0 team1-TFIDF_bnn_bnn
rna Q0 1018 29 104.0 team1-TFIDF_bnn_bnn
rna Q0 561 30 104.0 team1-TFIDF_bnn_bnn
rna Q0 751 31 104.0 team1-TFIDF_bnn_bnn
rna Q0 51 32 104.0 team1-TFIDF_bnn_bnn
rna Q0 280 33 104.0 team1-TFIDF_bnn_bnn
rna Q0 909 34 104.0 team1-TFIDF_bnn_bnn
rna Q0 664 35 104.0 team1-TFIDF_bnn_bnn
rna Q0 568 36 104.0 team1-TFIDF_bnn_bnn
rna Q0 2282 37 34.0 team1-TFIDF_bnn_bnn
rna Q0 518 38 34.0 team1-TFIDF_bnn_bnn
rna Q0 528 39 34.0 team1-TFIDF_bnn_bnn
rna Q0 942 40 34.0 team1-TFIDF_bnn_bnn
rna Q0 771 41 34.0 team1-TFIDF_bnn_bnn
rna Q0 2329 42 34.0 team1-TFIDF_bnn_bnn
rna Q0 693 43 34.0 team1-TFIDF_bnn_bnn
rna Q0 1019 44 34.0 team1-TFIDF_bnn_bnn
rna Q0 620 45 34.0 team1-TFIDF_bnn_bnn
rna Q0 722 46 34.0 team1-TFIDF_bnn_bnn
rna Q0 687 47 34.0 team1-TFIDF_bnn_bnn
rna Q0 299 48 34.0 team1-TFIDF_bnn_bnn
rna Q0 52 49 34.0 team1-TFIDF_bnn_bnn
domains Q0 2117 0 6.0 team1-TFIDF_bnn_bnn
domains Q0 972 1 6.0 team1-TFIDF_bnn_bnn
domains Q0 2153 2 2.0 team1-TFIDF_bnn_bnn
archive Q0 242 0 8.0 team1-TFIDF_bnn_bnn
archive Q0 604 1 8.0 team1-TFIDF_bnn_bnn
archive Q0 411 2 8.0 team1-TFIDF_bnn_bnn
archive Q0 2306 3 8.0 team1-TFIDF_bnn_bnn
estimation Q0 21 0 4.0 team1-TFIDF_bnn_bnn
estimation Q0 191 1 4.0 team1-TFIDF_bnn_bnn
estimation Q0 351 2 2.0 team1-TFIDF_bnn_bnn
technical replicates Q0 609 0 10.0 team1-TFIDF_bnn_bnn
technical replicates Q0 610 1 10.0 team1-TFIDF_bnn_bnn
technical replicates Q0 153 2 10.0 team1-TFIDF_bnn_bnn
technical replicates Q0 372 3 8.0 team1-TFIDF_bnn_bnn
technical replicates Q0 52 4 8.0 team1-TFIDF_bnn_bnn
technical replicates Q0 2140 5 4.0 team1-TFIDF_bnn_bnn
technical replicates Q0 232 6 4.0 team1-TFIDF_bnn_bnn
read mapping Q0 134 0 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 524 1 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 157 2 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 308 3 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 253 4 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 745 5 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 372 6 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 438 7 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 500 8 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 694 9 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 702 10 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 761 11 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 508 12 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 637 13 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 639 14 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 404 15 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 191 16 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 705 17 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 452 18 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 456 19 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 73 20 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 153 21 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 942 22 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 336 23 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 943 24 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 83 25 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 731 26 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 223 27 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 282 28 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 610 29 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 307 30 152.0 team1-TFIDF_bnn_bnn
read mapping Q0 2202 31 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2356 32 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 796 33 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 1014 34 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 908 35 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 375 36 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2306 37 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 449 38 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 518 39 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2088 40 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2149 41 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 716 42 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 462 43 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 174 44 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2145 45 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 2054 46 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 608 47 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 945 48 50.0 team1-TFIDF_bnn_bnn
read mapping Q0 5 49 50.0 team1-TFIDF_bnn_bnn
metagene Q0 608 0 2.0 team1-TFIDF_bnn_bnn
metagene Q0 516 1 2.0 team1-TFIDF_bnn_bnn
methylation Q0 2028 0 6.0 team1-TFIDF_bnn_bnn
methylation Q0 2051 1 4.0 team1-TFIDF_bnn_bnn
methylation Q0 505 2 4.0 team1-TFIDF_bnn_bnn
human genome Q0 1 0 166.0 team1-TFIDF_bnn_bnn
human genome Q0 135 1 166.0 team1-TFIDF_bnn_bnn
human genome Q0 375 2 166.0 team1-TFIDF_bnn_bnn
human genome Q0 27 3 166.0 team1-TFIDF_bnn_bnn
human genome Q0 817 4 166.0 team1-TFIDF_bnn_bnn
human genome Q0 351 5 166.0 team1-TFIDF_bnn_bnn
human genome Q0 608 6 166.0 team1-TFIDF_bnn_bnn
human genome Q0 736 7 166.0 team1-TFIDF_bnn_bnn
human genome Q0 481 8 166.0 team1-TFIDF_bnn_bnn
human genome Q0 796 9 166.0 team1-TFIDF_bnn_bnn
human genome Q0 565 10 166.0 team1-TFIDF_bnn_bnn
human genome Q0 107 11 166.0 team1-TFIDF_bnn_bnn
human genome Q0 438 12 166.0 team1-TFIDF_bnn_bnn
human genome Q0 628 13 166.0 team1-TFIDF_bnn_bnn
human genome Q0 527 14 166.0 team1-TFIDF_bnn_bnn
human genome Q0 285 15 166.0 team1-TFIDF_bnn_bnn
human genome Q0 568 16 166.0 team1-TFIDF_bnn_bnn
human genome Q0 120 17 166.0 team1-TFIDF_bnn_bnn
human genome Q0 288 18 166.0 team1-TFIDF_bnn_bnn
human genome Q0 418 19 166.0 team1-TFIDF_bnn_bnn
human genome Q0 442 20 166.0 team1-TFIDF_bnn_bnn
human genome Q0 316 21 166.0 team1-TFIDF_bnn_bnn
human genome Q0 774 22 166.0 team1-TFIDF_bnn_bnn
human genome Q0 807 23 166.0 team1-TFIDF_bnn_bnn
human genome Q0 702 24 166.0 team1-TFIDF_bnn_bnn
human genome Q0 449 25 166.0 team1-TFIDF_bnn_bnn
human genome Q0 195 26 166.0 team1-TFIDF_bnn_bnn
human genome Q0 709 27 166.0 team1-TFIDF_bnn_bnn
human genome Q0 404 28 166.0 team1-TFIDF_bnn_bnn
human genome Q0 328 29 166.0 team1-TFIDF_bnn_bnn
human genome Q0 462 30 166.0 team1-TFIDF_bnn_bnn
human genome Q0 604 31 166.0 team1-TFIDF_bnn_bnn
human genome Q0 558 32 72.0 team1-TFIDF_bnn_bnn
human genome Q0 2029 33 72.0 team1-TFIDF_bnn_bnn
human genome Q0 513 34 72.0 team1-TFIDF_bnn_bnn
human genome Q0 945 35 72.0 team1-TFIDF_bnn_bnn
human genome Q0 664 36 72.0 team1-TFIDF_bnn_bnn
human genome Q0 2098 37 72.0 team1-TFIDF_bnn_bnn
human genome Q0 228 38 72.0 team1-TFIDF_bnn_bnn
human genome Q0 110 39 72.0 team1-TFIDF_bnn_bnn
human genome Q0 951 40 72.0 team1-TFIDF_bnn_bnn
human genome Q0 2234 41 72.0 team1-TFIDF_bnn_bnn
human genome Q0 678 42 72.0 team1-TFIDF_bnn_bnn
human genome Q0 191 43 72.0 team1-TFIDF_bnn_bnn
human genome Q0 587 44 72.0 team1-TFIDF_bnn_bnn
human genome Q0 531 45 72.0 team1-TFIDF_bnn_bnn
human genome Q0 326 46 72.0 team1-TFIDF_bnn_bnn
human genome Q0 2241 47 72.0 team1-TFIDF_bnn_bnn
human genome Q0 584 48 72.0 team1-TFIDF_bnn_bnn
human genome Q0 278 49 72.0 team1-TFIDF_bnn_bnn
bedtools Q0 2242 0 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 70 1 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 2302 2 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 2119 3 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 427 4 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 27 5 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 2265 6 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 525 7 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 695 8 20.0 team1-TFIDF_bnn_bnn
bedtools Q0 2318 9 2.0 team1-TFIDF_bnn_bnn
data management Q0 9 0 266.0 team1-TFIDF_bnn_bnn
data management Q0 19 1 266.0 team1-TFIDF_bnn_bnn
data management Q0 418 2 266.0 team1-TFIDF_bnn_bnn
data management Q0 66 3 266.0 team1-TFIDF_bnn_bnn
data management Q0 242 4 266.0 team1-TFIDF_bnn_bnn
data management Q0 626 5 266.0 team1-TFIDF_bnn_bnn
data management Q0 627 6 266.0 team1-TFIDF_bnn_bnn
data management Q0 195 7 266.0 team1-TFIDF_bnn_bnn
data management Q0 372 8 266.0 team1-TFIDF_bnn_bnn
data management Q0 294 9 266.0 team1-TFIDF_bnn_bnn
data management Q0 196 10 266.0 team1-TFIDF_bnn_bnn
data management Q0 452 11 266.0 team1-TFIDF_bnn_bnn
data management Q0 328 12 266.0 team1-TFIDF_bnn_bnn
data management Q0 282 13 266.0 team1-TFIDF_bnn_bnn
data management Q0 584 14 266.0 team1-TFIDF_bnn_bnn
data management Q0 488 15 266.0 team1-TFIDF_bnn_bnn
data management Q0 73 16 266.0 team1-TFIDF_bnn_bnn
data management Q0 103 17 266.0 team1-TFIDF_bnn_bnn
data management Q0 308 18 266.0 team1-TFIDF_bnn_bnn
data management Q0 609 19 266.0 team1-TFIDF_bnn_bnn
data management Q0 83 20 266.0 team1-TFIDF_bnn_bnn
data management Q0 395 21 266.0 team1-TFIDF_bnn_bnn
data management Q0 283 22 266.0 team1-TFIDF_bnn_bnn
data management Q0 565 23 266.0 team1-TFIDF_bnn_bnn
data management Q0 343 24 266.0 team1-TFIDF_bnn_bnn
data management Q0 89 25 266.0 team1-TFIDF_bnn_bnn
data management Q0 92 26 266.0 team1-TFIDF_bnn_bnn
data management Q0 567 27 266.0 team1-TFIDF_bnn_bnn
data management Q0 351 28 266.0 team1-TFIDF_bnn_bnn
data management Q0 481 29 266.0 team1-TFIDF_bnn_bnn
data management Q0 29 30 266.0 team1-TFIDF_bnn_bnn
data management Q0 57 31 266.0 team1-TFIDF_bnn_bnn
data management Q0 610 32 266.0 team1-TFIDF_bnn_bnn
data management Q0 232 33 266.0 team1-TFIDF_bnn_bnn
data management Q0 456 34 78.0 team1-TFIDF_bnn_bnn
data management Q0 299 35 78.0 team1-TFIDF_bnn_bnn
data management Q0 2117 36 78.0 team1-TFIDF_bnn_bnn
data management Q0 253 37 78.0 team1-TFIDF_bnn_bnn
data management Q0 278 38 78.0 team1-TFIDF_bnn_bnn
data management Q0 899 39 78.0 team1-TFIDF_bnn_bnn
data management Q0 1014 40 78.0 team1-TFIDF_bnn_bnn
data management Q0 505 41 78.0 team1-TFIDF_bnn_bnn
data management Q0 771 42 78.0 team1-TFIDF_bnn_bnn
data management Q0 191 43 78.0 team1-TFIDF_bnn_bnn
data management Q0 702 44 78.0 team1-TFIDF_bnn_bnn
data management Q0 458 45 78.0 team1-TFIDF_bnn_bnn
data management Q0 462 46 78.0 team1-TFIDF_bnn_bnn
data management Q0 2202 47 78.0 team1-TFIDF_bnn_bnn
data management Q0 97 48 78.0 team1-TFIDF_bnn_bnn
data management Q0 350 49 78.0 team1-TFIDF_bnn_bnn
ancestry Q0 73 0 4.0 team1-TFIDF_bnn_bnn
ancestry Q0 481 1 2.0 team1-TFIDF_bnn_bnn
combat Q0 886 0 2.0 team1-TFIDF_bnn_bnn
storage Q0 587 0 2.0 team1-TFIDF_bnn_bnn
pasa Q0 969 0 2.0 team1-TFIDF_bnn_bnn
interactions Q0 673 0 14.0 team1-TFIDF_bnn_bnn
interactions Q0 567 1 14.0 team1-TFIDF_bnn_bnn
interactions Q0 2059 2 14.0 team1-TFIDF_bnn_bnn
interactions Q0 731 3 14.0 team1-TFIDF_bnn_bnn
interactions Q0 650 4 14.0 team1-TFIDF_bnn_bnn
interactions Q0 646 5 14.0 team1-TFIDF_bnn_bnn
interactions Q0 914 6 4.0 team1-TFIDF_bnn_bnn
interactions Q0 653 7 4.0 team1-TFIDF_bnn_bnn
ensembl Q0 741 0 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 2300 1 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 654 2 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 785 3 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 604 4 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 2036 5 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 2359 6 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 661 7 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 527 8 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 2101 9 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 2137 10 34.0 team1-TFIDF_bnn_bnn
ensembl Q0 522 11 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 21 12 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 2062 13 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 2384 14 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 2106 15 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 540 16 14.0 team1-TFIDF_bnn_bnn
ensembl Q0 939 17 14.0 team1-TFIDF_bnn_bnn
database Q0 2241 0 72.0 team1-TFIDF_bnn_bnn
database Q0 829 1 72.0 team1-TFIDF_bnn_bnn
database Q0 570 2 72.0 team1-TFIDF_bnn_bnn
database Q0 970 3 72.0 team1-TFIDF_bnn_bnn
database Q0 2130 4 72.0 team1-TFIDF_bnn_bnn
database Q0 673 5 72.0 team1-TFIDF_bnn_bnn
database Q0 1012 6 72.0 team1-TFIDF_bnn_bnn
database Q0 2095 7 72.0 team1-TFIDF_bnn_bnn
database Q0 817 8 72.0 team1-TFIDF_bnn_bnn
database Q0 802 9 72.0 team1-TFIDF_bnn_bnn
database Q0 815 10 72.0 team1-TFIDF_bnn_bnn
database Q0 818 11 72.0 team1-TFIDF_bnn_bnn
database Q0 2194 12 72.0 team1-TFIDF_bnn_bnn
database Q0 110 13 72.0 team1-TFIDF_bnn_bnn
database Q0 2092 14 72.0 team1-TFIDF_bnn_bnn
database Q0 118 15 72.0 team1-TFIDF_bnn_bnn
database Q0 677 16 72.0 team1-TFIDF_bnn_bnn
database Q0 972 17 72.0 team1-TFIDF_bnn_bnn
database Q0 2343 18 72.0 team1-TFIDF_bnn_bnn
database Q0 979 19 72.0 team1-TFIDF_bnn_bnn
database Q0 230 20 72.0 team1-TFIDF_bnn_bnn
database Q0 486 21 72.0 team1-TFIDF_bnn_bnn
database Q0 2323 22 72.0 team1-TFIDF_bnn_bnn
database Q0 709 23 72.0 team1-TFIDF_bnn_bnn
database Q0 283 24 72.0 team1-TFIDF_bnn_bnn
database Q0 2153 25 72.0 team1-TFIDF_bnn_bnn
database Q0 990 26 72.0 team1-TFIDF_bnn_bnn
database Q0 798 27 72.0 team1-TFIDF_bnn_bnn
database Q0 747 28 72.0 team1-TFIDF_bnn_bnn
database Q0 2065 29 72.0 team1-TFIDF_bnn_bnn
database Q0 488 30 20.0 team1-TFIDF_bnn_bnn
database Q0 2022 31 20.0 team1-TFIDF_bnn_bnn
database Q0 878 32 20.0 team1-TFIDF_bnn_bnn
database Q0 2169 33 20.0 team1-TFIDF_bnn_bnn
database Q0 548 34 20.0 team1-TFIDF_bnn_bnn
database Q0 887 35 20.0 team1-TFIDF_bnn_bnn
database Q0 282 36 20.0 team1-TFIDF_bnn_bnn
database Q0 527 37 20.0 team1-TFIDF_bnn_bnn
database Q0 196 38 20.0 team1-TFIDF_bnn_bnn
database Q0 623 39 20.0 team1-TFIDF_bnn_bnn
git Q0 112 0 4.0 team1-TFIDF_bnn_bnn
git Q0 751 1 4.0 team1-TFIDF_bnn_bnn
blat Q0 110 0 2.0 team1-TFIDF_bnn_bnn
gc content Q0 146 0 18.0 team1-TFIDF_bnn_bnn
gc content Q0 351 1 18.0 team1-TFIDF_bnn_bnn
gc content Q0 2259 2 18.0 team1-TFIDF_bnn_bnn
gc content Q0 228 3 18.0 team1-TFIDF_bnn_bnn
gc content Q0 620 4 18.0 team1-TFIDF_bnn_bnn
gc content Q0 884 5 18.0 team1-TFIDF_bnn_bnn
gc content Q0 2101 6 18.0 team1-TFIDF_bnn_bnn
gc content Q0 196 7 18.0 team1-TFIDF_bnn_bnn
gc content Q0 570 8 8.0 team1-TFIDF_bnn_bnn
gc content Q0 280 9 8.0 team1-TFIDF_bnn_bnn
gc content Q0 125 10 2.0 team1-TFIDF_bnn_bnn
parallel Q0 2257 0 12.0 team1-TFIDF_bnn_bnn
parallel Q0 525 1 12.0 team1-TFIDF_bnn_bnn
parallel Q0 2316 2 12.0 team1-TFIDF_bnn_bnn
parallel Q0 411 3 12.0 team1-TFIDF_bnn_bnn
parallel Q0 135 4 12.0 team1-TFIDF_bnn_bnn
parallel Q0 150 5 2.0 team1-TFIDF_bnn_bnn
structural Q0 2275 0 14.0 team1-TFIDF_bnn_bnn
structural Q0 2223 1 14.0 team1-TFIDF_bnn_bnn
structural Q0 796 2 14.0 team1-TFIDF_bnn_bnn
structural Q0 120 3 10.0 team1-TFIDF_bnn_bnn
structural Q0 329 4 10.0 team1-TFIDF_bnn_bnn
structural Q0 438 5 10.0 team1-TFIDF_bnn_bnn
structural Q0 271 6 10.0 team1-TFIDF_bnn_bnn
structural Q0 264 7 10.0 team1-TFIDF_bnn_bnn
repeat Q0 225 0 18.0 team1-TFIDF_bnn_bnn
repeat Q0 909 1 18.0 team1-TFIDF_bnn_bnn
repeat Q0 242 2 18.0 team1-TFIDF_bnn_bnn
repeat Q0 375 3 18.0 team1-TFIDF_bnn_bnn
repeat Q0 540 4 18.0 team1-TFIDF_bnn_bnn
repeat Q0 2275 5 18.0 team1-TFIDF_bnn_bnn
repeat Q0 2145 6 18.0 team1-TFIDF_bnn_bnn
repeat Q0 945 7 4.0 team1-TFIDF_bnn_bnn
repeat Q0 343 8 4.0 team1-TFIDF_bnn_bnn
impute2 Q0 336 0 4.0 team1-TFIDF_bnn_bnn
impute2 Q0 949 1 4.0 team1-TFIDF_bnn_bnn
mass spectrometry Q0 857 0 8.0 team1-TFIDF_bnn_bnn
mass spectrometry Q0 314 1 8.0 team1-TFIDF_bnn_bnn
mass spectrometry Q0 2111 2 4.0 team1-TFIDF_bnn_bnn
mass spectrometry Q0 609 3 2.0 team1-TFIDF_bnn_bnn
ngs Q0 81 0 14.0 team1-TFIDF_bnn_bnn
ngs Q0 191 1 14.0 team1-TFIDF_bnn_bnn
ngs Q0 146 2 14.0 team1-TFIDF_bnn_bnn
ngs Q0 422 3 14.0 team1-TFIDF_bnn_bnn
ngs Q0 2199 4 14.0 team1-TFIDF_bnn_bnn
ngs Q0 327 5 14.0 team1-TFIDF_bnn_bnn
ngs Q0 196 6 14.0 team1-TFIDF_bnn_bnn
ngs Q0 351 7 12.0 team1-TFIDF_bnn_bnn
ngs Q0 456 8 12.0 team1-TFIDF_bnn_bnn
bioawk Q0 974 0 4.0 team1-TFIDF_bnn_bnn
bioawk Q0 661 1 2.0 team1-TFIDF_bnn_bnn
deseq2 Q0 2375 0 14.0 team1-TFIDF_bnn_bnn
deseq2 Q0 909 1 14.0 team1-TFIDF_bnn_bnn
deseq2 Q0 584 2 14.0 team1-TFIDF_bnn_bnn
deseq2 Q0 2378 3 14.0 team1-TFIDF_bnn_bnn
deseq2 Q0 193 4 6.0 team1-TFIDF_bnn_bnn
deseq2 Q0 153 5 6.0 team1-TFIDF_bnn_bnn
deseq2 Q0 232 6 6.0 team1-TFIDF_bnn_bnn
sam Q0 289 0 34.0 team1-TFIDF_bnn_bnn
sam Q0 2242 1 34.0 team1-TFIDF_bnn_bnn
sam Q0 1002 2 34.0 team1-TFIDF_bnn_bnn
sam Q0 661 3 34.0 team1-TFIDF_bnn_bnn
sam Q0 2036 4 34.0 team1-TFIDF_bnn_bnn
sam Q0 157 5 34.0 team1-TFIDF_bnn_bnn
sam Q0 2306 6 34.0 team1-TFIDF_bnn_bnn
sam Q0 2088 7 34.0 team1-TFIDF_bnn_bnn
sam Q0 402 8 34.0 team1-TFIDF_bnn_bnn
sam Q0 404 9 34.0 team1-TFIDF_bnn_bnn
sam Q0 2363 10 16.0 team1-TFIDF_bnn_bnn
sam Q0 705 11 16.0 team1-TFIDF_bnn_bnn
sam Q0 14 12 16.0 team1-TFIDF_bnn_bnn
sam Q0 719 13 16.0 team1-TFIDF_bnn_bnn
sam Q0 98 14 16.0 team1-TFIDF_bnn_bnn
sam Q0 424 15 16.0 team1-TFIDF_bnn_bnn
sam Q0 908 16 16.0 team1-TFIDF_bnn_bnn
sam Q0 611 17 16.0 team1-TFIDF_bnn_bnn
long reads Q0 2051 0 150.0 team1-TFIDF_bnn_bnn
long reads Q0 135 1 150.0 team1-TFIDF_bnn_bnn
long reads Q0 289 2 150.0 team1-TFIDF_bnn_bnn
long reads Q0 418 3 150.0 team1-TFIDF_bnn_bnn
long reads Q0 449 4 150.0 team1-TFIDF_bnn_bnn
long reads Q0 372 5 150.0 team1-TFIDF_bnn_bnn
long reads Q0 375 6 150.0 team1-TFIDF_bnn_bnn
long reads Q0 120 7 150.0 team1-TFIDF_bnn_bnn
long reads Q0 1018 8 150.0 team1-TFIDF_bnn_bnn
long reads Q0 678 9 150.0 team1-TFIDF_bnn_bnn
long reads Q0 327 10 150.0 team1-TFIDF_bnn_bnn
long reads Q0 329 11 150.0 team1-TFIDF_bnn_bnn
long reads Q0 73 12 150.0 team1-TFIDF_bnn_bnn
long reads Q0 407 13 150.0 team1-TFIDF_bnn_bnn
long reads Q0 807 14 150.0 team1-TFIDF_bnn_bnn
long reads Q0 242 15 150.0 team1-TFIDF_bnn_bnn
long reads Q0 970 16 150.0 team1-TFIDF_bnn_bnn
long reads Q0 237 17 150.0 team1-TFIDF_bnn_bnn
long reads Q0 620 18 150.0 team1-TFIDF_bnn_bnn
long reads Q0 462 19 150.0 team1-TFIDF_bnn_bnn
long reads Q0 974 20 150.0 team1-TFIDF_bnn_bnn
long reads Q0 722 21 150.0 team1-TFIDF_bnn_bnn
long reads Q0 518 22 150.0 team1-TFIDF_bnn_bnn
long reads Q0 98 23 150.0 team1-TFIDF_bnn_bnn
long reads Q0 909 24 150.0 team1-TFIDF_bnn_bnn
long reads Q0 83 25 150.0 team1-TFIDF_bnn_bnn
long reads Q0 608 26 150.0 team1-TFIDF_bnn_bnn
long reads Q0 97 27 150.0 team1-TFIDF_bnn_bnn
long reads Q0 27 28 150.0 team1-TFIDF_bnn_bnn
long reads Q0 306 29 150.0 team1-TFIDF_bnn_bnn
long reads Q0 796 30 150.0 team1-TFIDF_bnn_bnn
long reads Q0 51 31 150.0 team1-TFIDF_bnn_bnn
long reads Q0 361 32 150.0 team1-TFIDF_bnn_bnn
long reads Q0 438 33 150.0 team1-TFIDF_bnn_bnn
long reads Q0 951 34 150.0 team1-TFIDF_bnn_bnn
long reads Q0 110 35 150.0 team1-TFIDF_bnn_bnn
long reads Q0 442 36 150.0 team1-TFIDF_bnn_bnn
long reads Q0 2036 37 52.0 team1-TFIDF_bnn_bnn
long reads Q0 2367 38 52.0 team1-TFIDF_bnn_bnn
long reads Q0 709 39 52.0 team1-TFIDF_bnn_bnn
long reads Q0 378 40 52.0 team1-TFIDF_bnn_bnn
long reads Q0 254 41 52.0 team1-TFIDF_bnn_bnn
long reads Q0 1001 42 52.0 team1-TFIDF_bnn_bnn
long reads Q0 2257 43 52.0 team1-TFIDF_bnn_bnn
long reads Q0 594 44 52.0 team1-TFIDF_bnn_bnn
long reads Q0 2098 45 52.0 team1-TFIDF_bnn_bnn
long reads Q0 2022 46 52.0 team1-TFIDF_bnn_bnn
long reads Q0 935 47 42.0 team1-TFIDF_bnn_bnn
long reads Q0 2302 48 42.0 team1-TFIDF_bnn_bnn
long reads Q0 2173 49 42.0 team1-TFIDF_bnn_bnn
next generation Q0 705 0 18.0 team1-TFIDF_bnn_bnn
next generation Q0 2275 1 18.0 team1-TFIDF_bnn_bnn
next generation Q0 2390 2 18.0 team1-TFIDF_bnn_bnn
next generation Q0 1001 3 18.0 team1-TFIDF_bnn_bnn
next generation Q0 242 4 18.0 team1-TFIDF_bnn_bnn
next generation Q0 462 5 18.0 team1-TFIDF_bnn_bnn
next generation Q0 709 6 18.0 team1-TFIDF_bnn_bnn
next generation Q0 2119 7 10.0 team1-TFIDF_bnn_bnn
next generation Q0 909 8 10.0 team1-TFIDF_bnn_bnn
next generation Q0 2067 9 10.0 team1-TFIDF_bnn_bnn
next generation Q0 994 10 10.0 team1-TFIDF_bnn_bnn
next generation Q0 81 11 10.0 team1-TFIDF_bnn_bnn
bigwig Q0 288 0 14.0 team1-TFIDF_bnn_bnn
bigwig Q0 608 1 14.0 team1-TFIDF_bnn_bnn
bigwig Q0 2088 2 14.0 team1-TFIDF_bnn_bnn
bigwig Q0 525 3 8.0 team1-TFIDF_bnn_bnn
bigwig Q0 2263 4 8.0 team1-TFIDF_bnn_bnn
bigwig Q0 708 5 8.0 team1-TFIDF_bnn_bnn
bigwig Q0 716 6 8.0 team1-TFIDF_bnn_bnn
bioanalyzer Q0 2056 0 2.0 team1-TFIDF_bnn_bnn
selectvariants Q0 974 0 2.0 team1-TFIDF_bnn_bnn
reads Q0 2051 0 150.0 team1-TFIDF_bnn_bnn
reads Q0 518 1 150.0 team1-TFIDF_bnn_bnn
reads Q0 135 2 150.0 team1-TFIDF_bnn_bnn
reads Q0 807 3 150.0 team1-TFIDF_bnn_bnn
reads Q0 970 4 150.0 team1-TFIDF_bnn_bnn
reads Q0 462 5 150.0 team1-TFIDF_bnn_bnn
reads Q0 120 6 150.0 team1-TFIDF_bnn_bnn
reads Q0 974 7 150.0 team1-TFIDF_bnn_bnn
reads Q0 407 8 150.0 team1-TFIDF_bnn_bnn
reads Q0 372 9 150.0 team1-TFIDF_bnn_bnn
reads Q0 722 10 150.0 team1-TFIDF_bnn_bnn
reads Q0 83 11 150.0 team1-TFIDF_bnn_bnn
reads Q0 242 12 150.0 team1-TFIDF_bnn_bnn
reads Q0 110 13 150.0 team1-TFIDF_bnn_bnn
reads Q0 237 14 150.0 team1-TFIDF_bnn_bnn
reads Q0 620 15 150.0 team1-TFIDF_bnn_bnn
reads Q0 608 16 150.0 team1-TFIDF_bnn_bnn
reads Q0 97 17 150.0 team1-TFIDF_bnn_bnn
reads Q0 909 18 150.0 team1-TFIDF_bnn_bnn
reads Q0 306 19 150.0 team1-TFIDF_bnn_bnn
reads Q0 98 20 150.0 team1-TFIDF_bnn_bnn
reads Q0 361 21 150.0 team1-TFIDF_bnn_bnn
reads Q0 27 22 150.0 team1-TFIDF_bnn_bnn
reads Q0 51 23 150.0 team1-TFIDF_bnn_bnn
reads Q0 438 24 150.0 team1-TFIDF_bnn_bnn
reads Q0 796 25 150.0 team1-TFIDF_bnn_bnn
reads Q0 289 26 150.0 team1-TFIDF_bnn_bnn
reads Q0 951 27 150.0 team1-TFIDF_bnn_bnn
reads Q0 442 28 150.0 team1-TFIDF_bnn_bnn
reads Q0 329 29 150.0 team1-TFIDF_bnn_bnn
reads Q0 73 30 150.0 team1-TFIDF_bnn_bnn
reads Q0 449 31 150.0 team1-TFIDF_bnn_bnn
reads Q0 375 32 150.0 team1-TFIDF_bnn_bnn
reads Q0 1018 33 150.0 team1-TFIDF_bnn_bnn
reads Q0 418 34 150.0 team1-TFIDF_bnn_bnn
reads Q0 327 35 150.0 team1-TFIDF_bnn_bnn
reads Q0 678 36 150.0 team1-TFIDF_bnn_bnn
reads Q0 1014 37 42.0 team1-TFIDF_bnn_bnn
reads Q0 945 38 42.0 team1-TFIDF_bnn_bnn
reads Q0 486 39 42.0 team1-TFIDF_bnn_bnn
reads Q0 2163 40 42.0 team1-TFIDF_bnn_bnn
reads Q0 2054 41 42.0 team1-TFIDF_bnn_bnn
reads Q0 508 42 42.0 team1-TFIDF_bnn_bnn
reads Q0 2173 43 42.0 team1-TFIDF_bnn_bnn
reads Q0 935 44 42.0 team1-TFIDF_bnn_bnn
reads Q0 402 45 42.0 team1-TFIDF_bnn_bnn
reads Q0 2318 46 42.0 team1-TFIDF_bnn_bnn
reads Q0 2302 47 42.0 team1-TFIDF_bnn_bnn
reads Q0 452 48 42.0 team1-TFIDF_bnn_bnn
reads Q0 2145 49 42.0 team1-TFIDF_bnn_bnn
edger Q0 2165 0 8.0 team1-TFIDF_bnn_bnn
edger Q0 2378 1 8.0 team1-TFIDF_bnn_bnn
edger Q0 2199 2 8.0 team1-TFIDF_bnn_bnn
edger Q0 457 3 2.0 team1-TFIDF_bnn_bnn
gnomad Q0 73 0 4.0 team1-TFIDF_bnn_bnn
gnomad Q0 933 1 2.0 team1-TFIDF_bnn_bnn
performance Q0 418 0 8.0 team1-TFIDF_bnn_bnn
performance Q0 525 1 8.0 team1-TFIDF_bnn_bnn
performance Q0 361 2 8.0 team1-TFIDF_bnn_bnn
performance Q0 403 3 8.0 team1-TFIDF_bnn_bnn
velvet Q0 2152 0 8.0 team1-TFIDF_bnn_bnn
velvet Q0 156 1 8.0 team1-TFIDF_bnn_bnn
velvet Q0 1019 2 8.0 team1-TFIDF_bnn_bnn
velvet Q0 1018 3 2.0 team1-TFIDF_bnn_bnn
sample database Q0 2065 0 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2323 1 72.0 team1-TFIDF_bnn_bnn
sample database Q0 673 2 72.0 team1-TFIDF_bnn_bnn
sample database Q0 802 3 72.0 team1-TFIDF_bnn_bnn
sample database Q0 829 4 72.0 team1-TFIDF_bnn_bnn
sample database Q0 1012 5 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2241 6 72.0 team1-TFIDF_bnn_bnn
sample database Q0 118 7 72.0 team1-TFIDF_bnn_bnn
sample database Q0 709 8 72.0 team1-TFIDF_bnn_bnn
sample database Q0 677 9 72.0 team1-TFIDF_bnn_bnn
sample database Q0 110 10 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2343 11 72.0 team1-TFIDF_bnn_bnn
sample database Q0 970 12 72.0 team1-TFIDF_bnn_bnn
sample database Q0 972 13 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2130 14 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2092 15 72.0 team1-TFIDF_bnn_bnn
sample database Q0 979 16 72.0 team1-TFIDF_bnn_bnn
sample database Q0 815 17 72.0 team1-TFIDF_bnn_bnn
sample database Q0 230 18 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2194 19 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2095 20 72.0 team1-TFIDF_bnn_bnn
sample database Q0 990 21 72.0 team1-TFIDF_bnn_bnn
sample database Q0 817 22 72.0 team1-TFIDF_bnn_bnn
sample database Q0 818 23 72.0 team1-TFIDF_bnn_bnn
sample database Q0 283 24 72.0 team1-TFIDF_bnn_bnn
sample database Q0 486 25 72.0 team1-TFIDF_bnn_bnn
sample database Q0 2153 26 72.0 team1-TFIDF_bnn_bnn
sample database Q0 798 27 72.0 team1-TFIDF_bnn_bnn
sample database Q0 747 28 72.0 team1-TFIDF_bnn_bnn
sample database Q0 570 29 72.0 team1-TFIDF_bnn_bnn
sample database Q0 692 30 68.0 team1-TFIDF_bnn_bnn
sample database Q0 627 31 68.0 team1-TFIDF_bnn_bnn
sample database Q0 19 32 68.0 team1-TFIDF_bnn_bnn
sample database Q0 318 33 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2119 34 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2310 35 68.0 team1-TFIDF_bnn_bnn
sample database Q0 36 36 68.0 team1-TFIDF_bnn_bnn
sample database Q0 962 37 68.0 team1-TFIDF_bnn_bnn
sample database Q0 271 38 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2361 39 68.0 team1-TFIDF_bnn_bnn
sample database Q0 238 40 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2324 41 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2140 42 68.0 team1-TFIDF_bnn_bnn
sample database Q0 1002 43 68.0 team1-TFIDF_bnn_bnn
sample database Q0 97 44 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2048 45 68.0 team1-TFIDF_bnn_bnn
sample database Q0 611 46 68.0 team1-TFIDF_bnn_bnn
sample database Q0 83 47 68.0 team1-TFIDF_bnn_bnn
sample database Q0 2097 48 68.0 team1-TFIDF_bnn_bnn
sample database Q0 951 49 68.0 team1-TFIDF_bnn_bnn
clustering Q0 2298 0 12.0 team1-TFIDF_bnn_bnn
clustering Q0 751 1 12.0 team1-TFIDF_bnn_bnn
clustering Q0 395 2 12.0 team1-TFIDF_bnn_bnn
clustering Q0 254 3 12.0 team1-TFIDF_bnn_bnn
clustering Q0 238 4 12.0 team1-TFIDF_bnn_bnn
clustering Q0 703 5 2.0 team1-TFIDF_bnn_bnn
10x genomics Q0 752 0 10.0 team1-TFIDF_bnn_bnn
10x genomics Q0 458 1 10.0 team1-TFIDF_bnn_bnn
10x genomics Q0 283 2 10.0 team1-TFIDF_bnn_bnn
10x genomics Q0 195 3 10.0 team1-TFIDF_bnn_bnn
10x genomics Q0 357 4 10.0 team1-TFIDF_bnn_bnn
10x genomics Q0 2356 5 8.0 team1-TFIDF_bnn_bnn
10x genomics Q0 329 6 8.0 team1-TFIDF_bnn_bnn
10x genomics Q0 693 7 8.0 team1-TFIDF_bnn_bnn
10x genomics Q0 779 8 4.0 team1-TFIDF_bnn_bnn
10x genomics Q0 308 9 4.0 team1-TFIDF_bnn_bnn
10x genomics Q0 771 10 4.0 team1-TFIDF_bnn_bnn
mauve Q0 266 0 2.0 team1-TFIDF_bnn_bnn
best practice Q0 2241 0 70.0 team1-TFIDF_bnn_bnn
best practice Q0 452 1 70.0 team1-TFIDF_bnn_bnn
best practice Q0 508 2 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2170 3 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2359 4 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2165 5 70.0 team1-TFIDF_bnn_bnn
best practice Q0 326 6 70.0 team1-TFIDF_bnn_bnn
best practice Q0 242 7 70.0 team1-TFIDF_bnn_bnn
best practice Q0 395 8 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2067 9 70.0 team1-TFIDF_bnn_bnn
best practice Q0 1001 10 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2390 11 70.0 team1-TFIDF_bnn_bnn
best practice Q0 107 12 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2059 13 70.0 team1-TFIDF_bnn_bnn
best practice Q0 745 14 70.0 team1-TFIDF_bnn_bnn
best practice Q0 1007 15 70.0 team1-TFIDF_bnn_bnn
best practice Q0 289 16 70.0 team1-TFIDF_bnn_bnn
best practice Q0 663 17 70.0 team1-TFIDF_bnn_bnn
best practice Q0 288 18 70.0 team1-TFIDF_bnn_bnn
best practice Q0 584 19 70.0 team1-TFIDF_bnn_bnn
best practice Q0 796 20 70.0 team1-TFIDF_bnn_bnn
best practice Q0 12 21 70.0 team1-TFIDF_bnn_bnn
best practice Q0 664 22 70.0 team1-TFIDF_bnn_bnn
best practice Q0 89 23 70.0 team1-TFIDF_bnn_bnn
best practice Q0 777 24 70.0 team1-TFIDF_bnn_bnn
best practice Q0 594 25 70.0 team1-TFIDF_bnn_bnn
best practice Q0 540 26 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2194 27 70.0 team1-TFIDF_bnn_bnn
best practice Q0 522 28 70.0 team1-TFIDF_bnn_bnn
best practice Q0 531 29 70.0 team1-TFIDF_bnn_bnn
best practice Q0 595 30 70.0 team1-TFIDF_bnn_bnn
best practice Q0 2088 31 16.0 team1-TFIDF_bnn_bnn
best practice Q0 407 32 16.0 team1-TFIDF_bnn_bnn
best practice Q0 2090 33 16.0 team1-TFIDF_bnn_bnn
best practice Q0 462 34 16.0 team1-TFIDF_bnn_bnn
best practice Q0 736 35 16.0 team1-TFIDF_bnn_bnn
best practice Q0 426 36 16.0 team1-TFIDF_bnn_bnn
best practice Q0 388 37 16.0 team1-TFIDF_bnn_bnn
best practice Q0 238 38 16.0 team1-TFIDF_bnn_bnn
best practice Q0 626 39 10.0 team1-TFIDF_bnn_bnn
best practice Q0 411 40 10.0 team1-TFIDF_bnn_bnn
best practice Q0 860 41 10.0 team1-TFIDF_bnn_bnn
best practice Q0 2202 42 10.0 team1-TFIDF_bnn_bnn
best practice Q0 125 43 10.0 team1-TFIDF_bnn_bnn
disease model Q0 193 0 60.0 team1-TFIDF_bnn_bnn
disease model Q0 191 1 60.0 team1-TFIDF_bnn_bnn
disease model Q0 62 2 60.0 team1-TFIDF_bnn_bnn
disease model Q0 125 3 60.0 team1-TFIDF_bnn_bnn
disease model Q0 321 4 60.0 team1-TFIDF_bnn_bnn
disease model Q0 251 5 60.0 team1-TFIDF_bnn_bnn
disease model Q0 196 6 60.0 team1-TFIDF_bnn_bnn
disease model Q0 57 7 60.0 team1-TFIDF_bnn_bnn
disease model Q0 568 8 60.0 team1-TFIDF_bnn_bnn
disease model Q0 73 9 60.0 team1-TFIDF_bnn_bnn
disease model Q0 2140 10 60.0 team1-TFIDF_bnn_bnn
disease model Q0 174 11 60.0 team1-TFIDF_bnn_bnn
disease model Q0 350 12 60.0 team1-TFIDF_bnn_bnn
disease model Q0 2346 13 60.0 team1-TFIDF_bnn_bnn
disease model Q0 1001 14 60.0 team1-TFIDF_bnn_bnn
disease model Q0 161 15 60.0 team1-TFIDF_bnn_bnn
disease model Q0 997 16 60.0 team1-TFIDF_bnn_bnn
disease model Q0 909 17 60.0 team1-TFIDF_bnn_bnn
disease model Q0 998 18 60.0 team1-TFIDF_bnn_bnn
disease model Q0 782 19 60.0 team1-TFIDF_bnn_bnn
disease model Q0 2375 20 60.0 team1-TFIDF_bnn_bnn
disease model Q0 378 21 60.0 team1-TFIDF_bnn_bnn
disease model Q0 2199 22 60.0 team1-TFIDF_bnn_bnn
disease model Q0 343 23 60.0 team1-TFIDF_bnn_bnn
disease model Q0 143 24 60.0 team1-TFIDF_bnn_bnn
disease model Q0 877 25 60.0 team1-TFIDF_bnn_bnn
disease model Q0 264 26 60.0 team1-TFIDF_bnn_bnn
disease model Q0 2073 27 12.0 team1-TFIDF_bnn_bnn
disease model Q0 195 28 12.0 team1-TFIDF_bnn_bnn
disease model Q0 2059 29 12.0 team1-TFIDF_bnn_bnn
disease model Q0 558 30 8.0 team1-TFIDF_bnn_bnn
disease model Q0 232 31 8.0 team1-TFIDF_bnn_bnn
disease model Q0 2359 32 8.0 team1-TFIDF_bnn_bnn
disease model Q0 326 33 8.0 team1-TFIDF_bnn_bnn
disease model Q0 829 34 2.0 team1-TFIDF_bnn_bnn
snap Q0 407 0 2.0 team1-TFIDF_bnn_bnn
